### ISSUE TITLE
Grupo CSS HUB

### ISSUE THREAD

**Issue by idlua** [training-center/study-groups#13]
Obs.: Nome temporário. :b

@akfzambrana,
@WendellAdriel,
@LarissaAbreu,
@roberthlima,
@SoullPower

Na issue #2 já formam 2 grupos, com os 5 primeiros e 5 demais comentários. Vamo nessa?!

**Comment by SoullPower** [comment]
Vamos lá :D

**Comment by WendellAdriel** [comment]
Bora lá!!!! :wink:

**Comment by SoullPower** [comment]
Cadê o povo do grupo ?

**Comment by idlua** [comment]
Quando eu chegar em casa vou mandar um e-mail pro pessoal pra ver se ainda vão continuar.. Não apareceram mais.

**Comment by Stoque** [comment]
Se sobrar uma vaga nesse grupo to dentro :)

**Comment by akfzambrana** [comment]
@idlua eu posso ficar como "ajudante" e assim vcs formam um grupo de 5 pessoas que queiram aprender, ja q esta sobrando :wink:

**Comment by woliveiras** [comment]
Galera, com base nas ideias do pessoal nas outras issues, criamos um time no slack.

Cada grupo de estudos pode criar um canal lá para conversar os assuntos de vocês.

Caso não queiram, não são obrigados a usar esse Slack viu, podem fazer como acharem melhor. :)

 https://ctgroups.herokuapp.com/

**Comment by marquinhusgoncalves** [comment]
Estou no banco de reservas, se precisar corro para o aquecimento...

**Comment by WendellAdriel** [comment]
Galera, decidam o nome do grupo aew!!!! :wink:

**Comment by davidasimoes** [comment]
Não é melhor fazer um grupo de CSS apenas? se ficar dois, o outro vai ficar morto, ja que ningem fala nada.

**Comment by idlua** [comment]
@akfzambrana show!
@Stoque bem-vindo! Formamos um grupo com 6 então, não há problema.
@WendellAdriel já que ninguém deu ideia coloquei **HUB**. :b Me coloca lá no Slack, pls. luanfrvicente@gmail.com
@davidasimoes acho que se formar um único grupo com todos vai ficar muito cheio, e isso dificulta muito pra quem tá iniciando. A ideia de grupos pequenos é pra tentar evitar isso e cada membro do grupo saber qual o nível de cada outro membro, assim cada um ensina o que sabe e aprende o que não. Você tá em algum dos dois grupos de CSS?

**Comment by Stoque** [comment]
@idlua show!

**Comment by LarissaAbreu** [comment]
@idlua Te enviei um convite pro slack xD

**Comment by Stoque** [comment]
@LarissaAbreu envia pra mim tb stoque@live.com ;)

**Comment by LarissaAbreu** [comment]
Enviei @Stoque

**Comment by Josue23** [comment]
https://github.com/LarissaAbreu envia pra mim tbm pls

On Monday, 28 March 2016, Lucas Stoque <notifications@github.com> wrote:

> @LarissaAbreu <https://github.com/LarissaAbreu> envia pra mim tb
> stoque@live.com <javascript:_e(%7B%7D,'cvml','stoque@live.com');> ;)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/training-center/sobre/issues/13#issuecomment-202664661>
>


--

**Comment by davidasimoes** [comment]
Ja tem channel no slack?

**Comment by WendellAdriel** [comment]
Galera desse grupo, criei o canal do Slack: #csshub :wink:

**Comment by LarissaAbreu** [comment]
@Josue23 qual o seu e-mail? Pra eu poder te enviar o convite...

Já sim, @davidasimoes... Se quiser me passa seu e-mail que eu te chamo pra lá também :smile:

**Comment by Josue23** [comment]
josuerodrigues@gmail.com

Tks 🖖



2016-03-29 9:48 GMT-03:00 Larissa Abreu <notifications@github.com>:

**Comment by LarissaAbreu** [comment]
Você já está lá, @Josue23 rsrsrs é só entrar nos canais agora xD

**Comment by Josue23** [comment]
Foi mal Larissa :)



2016-03-29 10:15 GMT-03:00 Larissa Abreu <notifications@github.com>:

**Comment by vicainelli** [comment]
Eu

**Comment by roberthlima** [comment]
roberth.limah@gmail.com

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
