### ISSUE TITLE
Grupo PHP PHPractice

### ISSUE THREAD

**Issue by SoullPower** [training-center/study-groups#14]
Primeiro grupo com os 5 primeiros para o estudo de PHP

Por favor me ajudem pessoal, não manjo quase nada do github, coloquem os nomes dos 5 primeiros do grupo de PHP por favor.

**Comment by alannaidon** [comment]
Estamos ae õ/

**Comment by SoullPower** [comment]
Não sei como fazer isso não =/ Estou começando agora a mecher aqui o github

**Comment by woliveiras** [comment]
@WendellAdriel
@fabricio1soares
@alannaidon
@davidasimoes
@ValdirCamargo

Pulei o @cvalentefilho, por que ele pode ficar em outra lista para ajudar mais a galera iniciante. :smile:

**Comment by SoullPower** [comment]
Ok, vlw @woliveiras

**Comment by davidasimoes** [comment]
coloca eu ai

**Comment by WendellAdriel** [comment]
Opa, beleza então galera!!! Vamos começar a movimentar!!!

Primeiro quero saber a experiência de vocês com PHP!!! :wink:
Falem aew pra gente começar a ver como vamos fazer!!!

**Comment by davidasimoes** [comment]
Eu estou começando a estudar php oo agora, já me apaixonei por php, quero tbm aprender a usar git.

**Comment by WendellAdriel** [comment]
Massa @davidasimoes!!!

Pra quem quiser dar uma olhada no meu site eu tenho um post com uma série de vídeos sobre PHP OO que gravei: http://education.codeshare.com.br/codecasts-php-oo/

Vamos aproveitar e falar de git também nesse grupo. O bom é a gente começar alguns estudos com coisas simples e depois ir melhorando o que a gente for fazendo a medida que evoluímos!!! :wink:

**Comment by davidasimoes** [comment]
@WendellAdriel  Perfeito!!

**Comment by alannaidon** [comment]
Buenas.

Eu me considero nível intermediário. Nunca trabalhei em empresa com php, mas estou desenvolvendo um sistema web para minha faculdade utilizando o laravel.

**Comment by fabricio1soares** [comment]
Sempre tive contato com php mas nunca aprofundei meu conhecimento, ja desenvolvi muitas coisas pequenas, mas sempre procedural, pretendo a partir de agora desenvolver OO, entendo bem o conceito e ja estudei sobre o assunto, mas nunca coloquei a mão na massa.

**Comment by SoullPower** [comment]
Eu também digamos que sou de nível intermediário, anexo com PHP quase diariamente contribuindo em pequenos projetos e sites e o que já fiz de mais legal com PHP foi uma rede social pro Instituto Federal onde estudava, foi o projeto final do curso. Tenho conhecimento na teoria de OO mas sei aplicar apenas em Java. Acho legal a gente definir um projeto a ser feito e ir alternando pessoas para postarem matérias ou coisas relacionadas a PHP  todo dia aqui.

**Comment by WendellAdriel** [comment]
Interessante, gostei muito da ideia @SoullPower. Acho legal a gente pensar em algum projeto open-source que ajude as pessoas e talz!!! Naquele post meu que comentei, a série de oito vídeos explica como utilizar OO no PHP, a primeira coisa que vou pedir é pra vcs darem uma olhada nos vídeos e caso tenham dúvida, me falar!!!

Vamos fazer alguns exercícios, etc durante um pequeno tempo pra praticar e já vamos definindo o projeto pra depois a gente criar o repo e definir as tarefas, etc!!! :wink:

O que vocês acham?

**Comment by SoullPower** [comment]
Acho muito bom, já vou começar a ver os vídeos da sua série e para todos que precisarem tenho bastante material pra estudar (livros, vídeo aulas, artigos) é só entrar em contato que eu posso disponibilizar

**Comment by WendellAdriel** [comment]
Opa, muito bom isso @SoullPower, com certeza os materiais vão ser bom pra todos!!!

Apenas pra começar uma conversa pra gente chegar em um rumo pro grupo. Vocês já utilizam/utilizaram algum Framework PHP, se sim, qual(is)? Qual vocês preferem pra gente utilizar em nosso projeto?

**Comment by SoullPower** [comment]
Eu nunca usei framework, tenho vontade mas não tive tempo ainda p estudar sobre algum, mas pelo que li na internet falam bastante sobre o laravel mas não sei nada sobre

**Comment by WendellAdriel** [comment]
Pra mim não existe assim essa história de ter o melhor Framework. Depende da situação, pessoalmente eu gosto muito do Laravel e uso bastante ele, mas gosto de outros como Symfony, Zend, etc. Mas pessoalmente amo o Laravel :heart:

**Comment by SoullPower** [comment]
Eu falei dele por ser o mais falado pela internet mas n sei nem como usar e nem qual é o melhor pra ser utilizadp

**Comment by WendellAdriel** [comment]
Não se preocupe depois de fazer alguns exercícios de OO pra pegar alguns conceitos importantes a gente começa a estudar ele!!! :wink:

**Comment by davidasimoes** [comment]
@SoullPower Gostei da ideia, nós poderiamos criar um projeto pro grupo, tipo uma rede social em php só para desenvolvedores

**Comment by SoullPower** [comment]
Opa boa idéia ;-D

**Comment by SoullPower** [comment]
Boa ideia :-D

**Comment by WendellAdriel** [comment]
@davidasimoes boa ideia cara!!! :wink:

**Comment by davidasimoes** [comment]
@WendellAdriel  Sobre o framework, e se criassemos nosso próprio framework? 
Além de não ficar dependente de terceiros, criamos um que atenda exatamente a necessidde.

**Comment by WendellAdriel** [comment]
Talvez os outros possam discordar, porém minha opinião é a seguinte...

Se for apenas pra fazer um micro framework bem simples pra estudo tudo bem...agora a gente querer criar um Framework pra fazer projetos, etc eu acho inviável, pois estaremos querendo como se diz: reinventar a roda...já existem N Frameworks no mercado, cada um com suas qualidades e seus defeitos e com certeza todo projeto que você vai precisar, um desses frameworks já irá satisfazer suas necessidades!!!! :wink:

**Comment by SoullPower** [comment]
Nisso eu tenho que concordar com o @WendellAdriel pois para criar um framework completo mesmo teríamos que ser no mínimo profissionais em PHP, mas criar um framework pequeno para fins de estudo acho muito legal.

**Comment by WendellAdriel** [comment]
Sim sim, vamos criar um projeto primeiro pra aplicar conhecimentos e desenvolver habilidades com algum Framework que pode dar espaço pra gente no mercado e depois começamos um projeto de um Micro Framework nosso oks galera?

**Comment by SoullPower** [comment]
ok :D

**Comment by WendellAdriel** [comment]
Galera, o @woliveiras vai criar uma Team no Slack e criar um channel pra cada grupo, aí deixaremos de utilizar essa issue igual um fórum ashusahushuahusa e vamos passar a utilizar o channel no Slack como principal meio de comunicação do grupo oks?!?!?!?!

**Comment by woliveiras** [comment]
É bom deixar a issue aqui pra saber quem está em cada grupo mano

**Comment by WendellAdriel** [comment]
Sim sim @woliveiras vamos deixar aqui, mas não vamos ficar usando pra debater e discutir as coisas e talz, se não vai ficar estranho

**Comment by woliveiras** [comment]
Tá lá galera! https://ctgroups.herokuapp.com/

**Comment by davidasimoes** [comment]
@woliveiras Como faço para entrar?

**Comment by WendellAdriel** [comment]
@davidasimoes clica no link aew do @woliveiras e cadastra seu email. Vai chegar um email de confirmação e aew é só seguir os passos!!! :wink:

**Comment by davidasimoes** [comment]
@WendellAdriel O meu ficou um botão please wait, e não chegou o email...

**Comment by WendellAdriel** [comment]
@woliveiras não é só comigo que ta acontecendo isso aew viu?!!??! Kkkkkk

**Comment by alannaidon** [comment]
@woliveiras  Mesma coisa comigo :<

**Comment by woliveiras** [comment]
Carai, ta endemonhado então mano! 
Verifiquem os emails de vocês, se chegou algo do Slack.

**Comment by WendellAdriel** [comment]
Aqui não chegou nada @woliveiras kkkkkk

**Comment by woliveiras** [comment]
Carai, ta encapetado... Ctz

Deixem seus emails aqui que eu já invito geral e vejo essa fita depois. :)

**Comment by WendellAdriel** [comment]
Kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk, o meu é wendelladriel.ti@gmail.com

**Comment by davidasimoes** [comment]
das.simoes@outlook.com  o meu.

**Comment by WendellAdriel** [comment]
Galera, vou criar o channel no Slack lá para nosso grupo, será o #phpractice

**Comment by alannaidon** [comment]
alannaidon@yahoo.com.br

Vlw!

**Comment by Josue23** [comment]
josuerodrigues@gmail.com



2016-03-28 14:53 GMT-03:00 ghaleon <notifications@github.com>:

**Comment by fabricio1soares** [comment]
ffs.fabricio@gmail.com
Também fui me registrar e o botão troca para Please Wait e no email nada.

**Comment by LarissaAbreu** [comment]
@fabricio1soares enviei o convite para o seu e-mail :)

**Comment by fabricio1soares** [comment]
Pessoal, estou desenvolvendo em OO mas me deparei com algumas dúvidas, vamos lá.
Criei a classe Categorias, no banco de dados ela possui 4 colunas (int id, string nome, text observacao e boolean host).
Tenho minha conexão PDO, e agora vou atualizar um registro no banco de dados, crio getters e setters e depois uma função que atualiza isso em banco de dados? Ou cada setter vai direto no campo da tabela? onde encontro um material que trabalhe com classes direto em banco de dados? pesquisei muito e ando cheio de dúvidas.
Abraços

**Comment by fabricio1soares** [comment]
Obrigado Larissa, já fiz o cadastro :D

**Comment by WendellAdriel** [comment]
@fabricio1soares para se trabalhar com classes direto no BD você tem que usar um ORM que nem tem o Doctrine, Eloquent, etc. Uma alternativa é você fazer esse mapeamento em um método que ao passar o objeto pro método ele faz o insert/update.

**Comment by fabricio1soares** [comment]
Seria uso de DAO?
Crio um CategoriaDAO com os metodos: select, insert, update delete? Seria correto criar um método "contagem" que retorna a quantidade de itens nesta categoria?

**Comment by WendellAdriel** [comment]
@fabricio1soares seria mais para utilizar o Repository Pattern que será responsável por todas operações no BD para sua classe.

**Comment by fabricio1soares** [comment]
Possui algum material sobre isso para eu ler? Pode ser em inglês mesmo, não sei o que é Repository Pattern.

**Comment by fabricio1soares** [comment]
Outra dúvida que venho tentando contornar há um tempo, gostaria de sugestões:
Tenho um pequeno sistema, para cadastrar computadores na empresa, cada computador possui um registro na tabela equipamentos com número de patrimônio, local, marca, modelo, etc. Na tela de alteração do equipamento, tenho o formulário em html com um campo hidden contendo o valor id do equipamento na tabela do BD, mas uma pessoa mal intencionada pode alterar esse id e facilmente alterar os dados de vários equipamentos, que maneiras posso mitigar/dificultar esta possibilidade?

**Comment by WendellAdriel** [comment]
@fabricio1soares dá uma olhada nesse repo aqui: https://github.com/WendellAdriel/DesignPatternsPHP que tem diversos Design Patterns com exemplos em PHP.

Ao problema que falou, você pode adicionar um token de segurança, tem um exemplo básico aqui: http://phpsecurity.org/code/ch02-5

**Comment by fabricio1soares** [comment]
Veja se entendi: Quando o usuário acessar a página de alterar o equipamento eu gero o token e guardo na sessão, quando receber os inputs dos formulários verifico se o token que veio junto com o formulário é o mesmo na sessão, caso positivo continuo a execução, assim que devo implementar?

**Comment by WendellAdriel** [comment]
@fabricio1soares isso, pode ser dessa maneira sim

**Comment by roberthlima** [comment]
roberth.limah@gmail.com

**Comment by fabricio1soares** [comment]
Pessoal, podem avaliar minha construção OO?
Estou em dúvida se fiz tudo corretamente:

Categoria.php
```
Class Categoria {
		private $id;
		private $name;
		private $notes;
		private $host;
		private $electric;
		
		public function __construct($id = NULL, $name = NULL, $notes = NULL, $host = NULL, $electric = NULL){
            $this->id = $id;
            $this->name = $name;
            $this->notes = $notes;
            $this->host = $host;
            $this->electric = $electric;
       }
		
		public function setId($id){
			$this->id = $id;
		}
		
		public function setName($name){
			$this->name = $name;
		}
		
		public function setNotes($notes){
			$this->notes = $notes;
		}
		
		public function setHost($host){
			$this->host = $host;
		}
		
		public function setElectric($electric){
			$this->electric = $electric;
		}
		
		public function getId(){
			return $this->id;
		}
		
		public function getName(){
			return $this->name;
		}
		
		public function getNotes(){
			return $this->notes;
		}
		
		public function isHost(){
			return $this->host;
		}
		
		public function isElectric(){
			return $this->electric;
		}
	}
```

CategoriaDAO.php
```
	Class CategoriaDAO extends DB {
		
		public function insert(Categoria $categoria){
			$statement = $this->connection->prepare("INSERT INTO categorias (nome, obs, host, eletrico) VALUES (?, ?, ?, ?)");
			$statement->execute(array($categoria->getName(), $categoria->getNotes(), $categoria->isHost(), $categoria->isElectric())); 
			$categoria->setId($this->connection->lastInsertId());
			return $categoria;	
		}
		
		public function update(Categoria $categoria){
			
		}
		
	}

```
DB.php
```
	Class DB {
		
		private $host = 'localhost';
		private $user = 'root';
		private $password = '';
		private $database = 'infra';	
		public $connection;

		public function __construct() {
			try {
				$this->connection = new PDO('mysql:host=' . $this->host . ';dbname=' . $this->database, $this->user, $this->password);
				$this->connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			}
			catch(PDOException $e) {
				return $e->getMessage();
			}
		}
	}

AutoLoader.php
class Autoloader {
	public static function loader($class) {
		$filename = $class . '.php';
		$file = '' . $filename; //insert the path between the quotes
		if (!file_exists($file)) {
			return false;
		}
		include $file;
	}
}
```


Exemplo de uso:
```
require_once("AutoLoader.php");
spl_autoload_register('Autoloader::loader');

$categoria = new Categoria();
$categoriaDAO = new CategoriaDAO();

$categoria->setName("Switch");
$categoria->setNotes("Observação");
$categoria->setHost(true);
$categoria->setElectric(false);

$categoria = $categoriaDAO->insert($categoria);
```

Minha maior dúvida é se a implementação DAO <==> PDO está correta, abraços!

**Comment by WendellAdriel** [comment]
@fabricio1soares dei uma olhada rápida apenas, mas parece estar de boas!!! :wink:

**Comment by ktquez** [comment]
Galera, se alguém sair, gostaria de participar.
Qualquer coisa me avisem, vlw

**Comment by mauraodev** [comment]
Add no channel por favor

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
