### ISSUE TITLE
Grupo MongoDB DBmon

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#19]
Primeiro grupo de estudos de MongoDB.

**Comment by WendellAdriel** [comment]
Galera nosso channel no slack é #dbmon

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
