### ISSUE TITLE
Grupo Node.js NodejStudies

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#20]
Primeiro grupo de estudos de Node.js:

Eu (kkkk)
@LarissaAbreu
@fauker
@VictorVoid
@lucasbento
@karlprieb

**Comment by WendellAdriel** [comment]
Galera, decidam o nome do grupo aew!!!! :wink:

**Comment by fauker** [comment]
NodejStudies. :joy:  

Acho que pode ser algo bem normal mesmo, ou do jeito que já está.

**Comment by karlprieb** [comment]
Ainda posso entrar no grupo? :)

**Comment by WendellAdriel** [comment]
Vou te colocar ali na lista @karlprieb!!!! :wink:

**Comment by WendellAdriel** [comment]
Galera desse grupo, criei o canal do Slack: #nodejstudies :wink:

**Comment by fauker** [comment]
@WendellAdriel pra entrar no canal do Slack não precisa ser convidado? Se sim, meu e-mail -> eskerlucas1@gmail.com.

**Comment by LarissaAbreu** [comment]
Enviado @fauker :bowtie:

**Comment by WendellAdriel** [comment]
Muito obrigado @LarissaAbreu :wink:

**Comment by karlprieb** [comment]
@LarissaAbreu se puder me invita também :) karl@prieb.me

**Comment by VictorVoid** [comment]
pra mim também!! victor.0w3@hotmail.com

**Comment by renancarvalhoo** [comment]
O meu tb renan.azevedo.carvalho@gmail.com

2016-03-29 16:25 GMT-03:00 Victor Igor <notifications@github.com>:

**Comment by LarissaAbreu** [comment]
Feito @renancarvalhoo :)

**Comment by rogeralbinoi** [comment]
Ainda cabe mais um no grupo?

**Comment by CaduFerreira** [comment]
mais 2? hahaha

**Comment by woliveiras** [comment]
Acho que é só chamar a galera no Slack que é sucesso! 😄

**Comment by Jessica7** [comment]
Gostaria de fazer parte tbm!

**Comment by woliveiras** [comment]
Só chegar no Slack e agitar lá @Jessica7 \o/

https://ctgroups.herokuapp.com/

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
