### ISSUE TITLE
Grupo Python HUB

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#21]
Primeiro grupo de estudos de Python:

Eu
@LarissaAbreu
@zalvesnatan
@NokhyPlemun
@Josue23

**Comment by Josue23** [comment]
Pessoal, como está o conhecimento de Pythin de vcs?

Abs!



2016-03-28 15:40 GMT-03:00 Wendell Adriel <notifications@github.com>:

**Comment by WendellAdriel** [comment]
O meu tá no básico do básico do básico kkkkk

**Comment by WendellAdriel** [comment]
Galera, decidam o nome do grupo aew!!!! :wink:

**Comment by Josue23** [comment]
haha

melhor basicão mesmo



2016-03-28 16:08 GMT-03:00 Wendell Adriel <notifications@github.com>:

**Comment by LarissaAbreu** [comment]
O meu conhecimento em Python é 0 atualmente rsrs

**Comment by Josue23** [comment]
Eu manjo um pouquinho de Python, posso ajudar



2016-03-29 9:42 GMT-03:00 Larissa Abreu <notifications@github.com>:

**Comment by WendellAdriel** [comment]
Então você que irá nos ajudar @Josue23 :wink:

Cria um nome aew galera pra eu criar o canal no Slack pra gente

**Comment by Josue23** [comment]
Ajudo sim com prazer

Quem tiver afim de um curso muito bom eu recomendo esse:
https://www.youtube.com/watch?v=6La690qlH5w&list=PLUukMN0DTKCtbzhbYe2jdF4cr8MOWClXc

é how de bola
a gente poderia seguir esse material



2016-03-29 9:59 GMT-03:00 Wendell Adriel <notifications@github.com>:

**Comment by NokhyPlemun** [comment]
Eu sei um pouco sobre python, so não sei a parte de web.
Aprendi python aqui: https://www.youtube.com/channel/UCmjj41YfcaCpZIkU-oqVIIw/featured

**Comment by LarissaAbreu** [comment]
@zalvesnatan você já está no nosso canal do slack? Se sim, qual o seu nome/e-mail lá? Se não, acessa esse link aqui (https://ctgroups.herokuapp.com/) e entra lá pra gente poder começar xD

**Comment by zalvesnatan** [comment]
@LarissaAbreu  Prontinho, desculpa a demora.

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
