### ISSUE TITLE
Grupo de estudos Python - 2

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#22]
Grupo para montar segundo grupo de estudos de Python, pois o primeiro deu sete pessoas, e o grupo foi formado com as cinco primeiras.

As duas pessoas que já estão nesse grupo são:
@Z4yon
@OtavioRMachado

**Comment by heltonalves99** [comment]
Posso participar ?

**Comment by WendellAdriel** [comment]
Lógico @heltonalves99, só aguardar fechar o grupo pra começar as paradas!!!! :wink:

**Comment by jeanpaulo** [comment]
Olá pessoal. Como está o grupo?
Estou querendo aprender Python também.

**Comment by woliveiras** [comment]
Fala @jeanpaulo 

A galera está trocando mais ideia via [Slack](https://ctgroups.herokuapp.com/). :smile:

**Comment by jeanpaulo** [comment]
Obrigado @woliveiras 
Já estou por lá ;)
Como eu não vi grupo por lá, achei que tivessem formado grupos específicos e privados.
Vlw!

**Comment by woliveiras** [comment]
Show de bola @jeanpaulo :smile: 

Só sucesso!

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
