### ISSUE TITLE
Grupo CSS POG

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#23]
Segundo grupo para estudar CSS:

@idlua 
@thiagorosario
@alannaidon
@davidasimoes
@lucasbento

**Comment by alannaidon** [comment]
Vamo dalhe !

**Comment by WendellAdriel** [comment]
Galera, decidam o nome do grupo aew!!!! :wink:

**Comment by idlua** [comment]
@WendellAdriel tu colocou nossos nomes em 2 grupos de CSS diferentes cara! kkk

**Comment by WendellAdriel** [comment]
É pra gente aprender em dobro @idlua ashushuahusahusahusahusahusahusahu, não tinha percebido

**Comment by woliveiras** [comment]
Galera, o auto invite no Slack já está OK

**Comment by idlua** [comment]
@WendellAdriel KKKKKKKKKKKKKKKKKKKKKKK rachei!! Aí sim!

**Comment by adamsalves** [comment]
Se tiver vaga ainda, gostaria de participar :)

**Comment by davidasimoes** [comment]
Vai sair alguma coisa daqui?

**Comment by LarissaAbreu** [comment]
Vai sim, @davidasimoes.. Na verdade estamos esperando os membros desse grupo decidirem um nome para o grupo para poder criar uma issue pra ele e um canal dele no slack (ou podemos colocar o nome que já está aqui mesmo se quiserem :) ).

**Comment by davidasimoes** [comment]
Que tal o nome POG?

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
