### ISSUE TITLE
Grupo JavaScript HUB

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#24]
Primeiro grupo com as seis primeiras pessoas da issue #3 para estudar JavaScript:

@akfzambrana
Eu
@LarissaAbreu
@idlua 
@ktquez
@lucasaugustofrontend

**Comment by WendellAdriel** [comment]
Galera, decidam o nome do grupo aew!!!! :wink:

**Comment by idlua** [comment]
Pode ser HUB, como coloquei no CSS. É fácil de memorizar e tem ligação com onde estamos. :b

**Comment by WendellAdriel** [comment]
Galera desse grupo, criei o canal no Slack desse grupo: #jshub :wink:

**Comment by woliveiras** [comment]
Galera, o auto invite no Slack já está OK

**Comment by lucasaugustofrontend** [comment]
Eu ainda não recebir nenhum convite
Em 29 de mar de 2016 11:28, "William Oliveira" <notifications@github.com>
escreveu:

**Comment by LarissaAbreu** [comment]
Tentou acessando esse link http://ctgroups.herokuapp.com/, @lucasaugustofrontend?

**Comment by vicainelli** [comment]
Eu

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
