### ISSUE TITLE
Grupo JavaScript JS Studies

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#25]
Segundo grupo com as cinco primeiras pessoas da issue #3 para estudar JavaScript:

@thiagorosario
@cvalentefilho
@joaocarvalhowd
@ggstroligo
@lucasbento
@banduka

**Comment by WendellAdriel** [comment]
Galera, decidam o nome do grupo aew!!!! :wink:

**Comment by ktquez** [comment]
Opa, se tiver vaga ainda, estou nessa.

**Comment by LarissaAbreu** [comment]
@thiagorosario, @joaocarvalhowd, @ggstroligo e @banduka vocês já estão lá no nosso canal do slack? Se sim, qual o nome/e-mail de vocês lá? Se não, por favor acessem esse link aqui (https://ctgroups.herokuapp.com/) e entrem lá pro grupo começar a estudar :grin:

**Comment by joaocarvalhowd** [comment]
Opa, entrando! :smiley:

**Comment by jonathanslima** [comment]
@ktquez somos dois. Tem que ser cinco pra formar o grupo, pelo que entendi

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
