### ISSUE TITLE
Grupo de estudos Ionic

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#26]
Formação de grupo para estudar sobre desenvolvimento de apps híbridos utilizando Ionic.

**Comment by GuimaP** [comment]
Eu quero

**Comment by khaosdoctor** [comment]
To a fim de participar

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
