### ISSUE TITLE
Grupo de estudos NativeScript

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#27]
Formação de grupo para estudar sobre desenvolvimento de apps híbridos utilizando NativeScript.

**Comment by GuimaP** [comment]
Up

**Comment by GuimaP** [comment]
Up

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
