### ISSUE TITLE
Grupo de estudos Vue.js

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#28]
Formação de grupo para estudar sobre Vue.js.

**Comment by karlprieb** [comment]
Topo :)

**Comment by woliveiras** [comment]
Galera, o auto invite no Slack já está OK

**Comment by brunoravanhani** [comment]
Eu to dentro

**Comment by adamsalves** [comment]
Quero participar :)

**Comment by ktquez** [comment]
Estou dentro galera, gostaria de um convite para o slack, vlw

**Comment by karlprieb** [comment]
Falta 1 para montarmos o grupo :)

**Comment by CallMeFabioo** [comment]
Eu topo hein. :)

**Comment by karlprieb** [comment]
Fechamos o grupo? :)

**Comment by adamsalves** [comment]
Acho que sim @karlprieb :+1:  Precisa de um nome para o grupo, não é?

**Comment by karlprieb** [comment]
Precisamos, sou meio ruim com nomes, mas vai uma sugestão Vue(view)Ex(explorers). Sei la hehehe

**Comment by adamsalves** [comment]
Massa, gostei! Fica aberto aí pra mais sugestões!

**Comment by CallMeFabioo** [comment]
Gostei também!

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
