### ISSUE TITLE
Grupo de estudos Android Studio

### ISSUE THREAD

**Issue by LarissaAbreu** [training-center/study-groups#32]
Formação de grupo para estudar Android Studio.

**Comment by WendellAdriel** [comment]
Conta comigo!!!! :wink:

**Comment by diasEduardo** [comment]
opa, sei pouco mas me enteressa bastante =q
parafraseando o @WendellAdriel  "conte comigo!!!!"

**Comment by JeffersonCarvalh0** [comment]
Opa, to interessado!

**Comment by woliveiras** [comment]
Ai tem coisa bagarai ein! \o/

**Comment by WendellAdriel** [comment]
Esse aqui acho que o @woliveiras que manja mais poderia ajudar, oq acha mano!?!??! :wink:

**Comment by woliveiras** [comment]
É nada mano, manjo bem pouco... Mas posso ajudar sim. :smile:

**Comment by woliveiras** [comment]
Galera, o auto invite no Slack já está OK

**Comment by gamartins** [comment]
Qual o canal ?

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
