### ISSUE TITLE
Grupo de estudos - PhoneGap & Cordova

### ISSUE THREAD

**Issue by metractive** [training-center/study-groups#33]
**Formação de grupo para estudar PhoneGap com Cordova**

Já desenvolvi 3 aplicativos em PhoneGap, mas utilizei o framework jQuery Mobile na época que iniciei os projetos. Mas infelizmente, ao final do desenvolvimento descobri um framework muito melhor, chamado OnsenUI que até utiliza Angular.js. Creio que o objetivo desse grupo de estudos seria compartilhar conhecimentos e aprendermos a lidar com o PhoneGap junto com o Cordova, utilizando o framework OnsenUI para as interfaces e interações:
https://onsen.io/

O Cordova serve justamente para a compilação do PhoneGap através da ferramenta da Adobe, chamada PhoneGap Build ou podemos utilizar (no qual eu prefiro) o Cordova CLI.

Para iniciar o grupo de estudos, seguem alguns links interessantes:
https://cordova.apache.org/docs/en/latest/guide/overview/
https://onsen.io/guide/overview.html

Projeto citado desenvolvido com PhoneGap:
http://bit.ly/1PFr3Xl

**Comment by fabricio1soares** [comment]
Acompanhando!

**Comment by ferreiradev** [comment]
Acompanhando

**Comment by brunoravanhani** [comment]
Acompanhando

**Comment by GuimaP** [comment]
Topo

**Comment by khaosdoctor** [comment]
To dentro tbm

**Comment by MetalWingsWeb** [comment]
Fico feliz que estão interessados, essa semana estou terminando de me organizar e pretendo pedir para criarem um grupo no slack pra gente. Alguém sugere algum nome?

**Comment by khaosdoctor** [comment]
Não é melhor criar um canal no slack do CT?

**Comment by MetalWingsWeb** [comment]
Sim, seria lá mesmo que eu iria pedir @khaosdoctor

**Comment by khaosdoctor** [comment]
A gente poderia adotar um prefixo tipo [GE] - Phonegap & Cordova de "Grupo de Estudos" e criar lá, acho que não é todo mundo que tem a permissão pra criar.

**Comment by metractive** [comment]
Entrei de férias e queria saber se ainda estão interessados por aqui?

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
