### ISSUE TITLE
Grupo de estudos Inglês

### ISSUE THREAD

**Issue by LarissaAbreu** [training-center/study-groups#34]
Formação de grupo para estudar e treinar nosso querido Inglês.

PS.: Esse será um grupo sem limite de integrantes :sunglasses:

**Comment by WendellAdriel** [comment]
I'm in!!! :wink:

**Comment by Josue23** [comment]
I'm in

On Wednesday, 30 March 2016, ghaleon <notifications@github.com> wrote:

> If everyone agree that we make something like a "Hangout" where we ONLY
> talk in english.
> I'm 9999% in !!! I really miss some friends to practice.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/training-center/sobre/issues/34#issuecomment-203661488>
>


--

**Comment by JeffersonCarvalh0** [comment]
Interesting idea. I'm in!

**Comment by MetalWingsWeb** [comment]
I'd like to talk in this hangout! But my conversation english is embarrassing.

**Comment by NokhyPlemun** [comment]
eu

**Comment by LarissaAbreu** [comment]
Vocês já estão lá no slack do CT @JeffersonCarvalh0, @MetalWingsWeb e @NokhyPlemun?

**Comment by MetalWingsWeb** [comment]
Sim, meu nome está como marcelo-mw

**Comment by alannaidon** [comment]
Então, alguma ideia pro speaking ? TS / Mumble /Skype ...

**Comment by lucasbento** [comment]
Também to dentro, posso ajudar bastante com a parte gramatical!

**Comment by JeffersonCarvalh0** [comment]
Sou noob em github, como eu verifico isso?

**Comment by LarissaAbreu** [comment]
@JeffersonCarvalh0 pra entrar no slack é só acessar esse link https://ctgroups.herokuapp.com/ :smile:

**Comment by NokhyPlemun** [comment]
eu to la como Nokhy!

**Comment by JeffersonCarvalh0** [comment]
@LarissaAbreu Ahh, entendi, kkk... Já entrei lá, meu nome é jeffersoncarvalho

**Comment by alannaidon** [comment]
@LarissaAbreu  Então, quando começamos, povo e pova  ? 
(:

**Comment by woliveiras** [comment]
Pow, esse grupo aqui poderia ter até mais que 5 pessoas ein... Que tal galera?

Ou então, dava pra fazer um grupo só de hangouts com conversação em inglês. - Falar da vida, das tretas, do mundo, sobre como resolver os problemas do planeta... Essas coisas.

**Comment by renancarvalhoo** [comment]
i'm in
Em 31/03/2016 13:08, "ghaleon" <notifications@github.com> escreveu:

**Comment by LarissaAbreu** [comment]
Então @woliveiras... Esse grupo não tem limitação de integrantes rs já tem uma galerinha lá no slack e, pelo que eu vi, eles estão tentando marcar um hangout pra ajudar na conversação :wink:

**Comment by woliveiras** [comment]
Shooow

**Comment by grilo208** [comment]
O grupo ainda está ativo  ? gostaria de entrar.

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
