### ISSUE TITLE
Grupo de estudos React.js

### ISSUE THREAD

**Issue by henriquesosa** [training-center/study-groups#35]
Formação de grupo para estudar e treinar React.js. :)

**Comment by camilatigre** [comment]
Não sei direito como vai funcionar a issue mas acho que esse link pode ser muito útil: http://courses.reactjsprogram.com/courses/reactjsfundamentals

Já me inscrevi (:

**Comment by LarissaAbreu** [comment]
Eu topo ein xD

**Comment by henriquesosa** [comment]
A ideia é montar um grupo para difundir e aprender mais a ideia. Acredito que com mais gente aceitando podemos montar um slack ou um gitter para ir falando.

**Comment by lucasbento** [comment]
@henriquesosa opa, tô dentro!

**Comment by marquinhusgoncalves** [comment]
Tô dentro

**Comment by ktquez** [comment]
Estou nessa

**Comment by leocavalcante** [comment]
:+1:

**Comment by metractive** [comment]
Ainda tá vivo esse grupo? To dentro!

**Comment by woliveiras** [comment]
\o/

Invoca a galera no nosso [Slack](https://ctgroups.herokuapp.com/) @metractive

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
