### ISSUE TITLE
Grupo HTML HUB

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#36]
Primeiro grupo para estudar HTML:

@SoulPower
@banduka
@LarissaAbreu 
@davidasimoes
@Stoque
@Josue23

**Comment by LarissaAbreu** [comment]
@banduka você já está no nosso canal do slack? Se sim, qual o seu nome/e-mail lá? Se não, acessa esse link aqui (https://ctgroups.herokuapp.com/) e entra lá pra gente começar a estudar XD

**Comment by Josue23** [comment]
Olá pessoal,
Sugiro que a gente tente seguir esse curso.
https://www.edx.org/course/html5-introduction-w3cx-html5-0x

Em 5 de abril de 2016 19:31, Larissa Abreu <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
