### ISSUE TITLE
Grupo WordPress HUB

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#37]
Primeiro grupo para estudar WordPress:

@cvalentefilho
@heliomsolivas
@LarissaAbreu 
@marquinhusgoncalves
@vicainelli

**Comment by cvalentefilho** [comment]
O que vamos aprender?

**Comment by WendellAdriel** [comment]
Não estou no grupo, mas acho que você é o mais experiente @cvalentefilho, então vc fica administrando aew o grupo!!!! :wink:

**Comment by cvalentefilho** [comment]
Blz @WendellAdriel

**Comment by LarissaAbreu** [comment]
Inclusive seria legal você entrar no canal do slack, @cvalentefilho :)

**Comment by cvalentefilho** [comment]
Qual é o canal?

**Comment by LarissaAbreu** [comment]
https://ctgroups.herokuapp.com/ esse aqui :bowtie:

**Comment by cvalentefilho** [comment]
@LarissaAbreu me add no cal do WP por favor?

**Comment by cvalentefilho** [comment]
Galera, Precisamos definir um tema para iniciarmos o projeto alguém tem uma ideia?

**Comment by heliomsolivas** [comment]
Tem que ver o nivel do pessoal com wordpress

**Comment by cvalentefilho** [comment]
Então @heliomsolivas, acho bacana iniciarmos do zero. Desde a instalacao e configuracao e com o passar do tempo vamos definindo os tópicos.

O que acham?

Mas o legal seria definirmos algo para desenvolvermos em cima, tipo um tema para a criação do site em WordPress.

**Comment by heliomsolivas** [comment]
@cvalentefilho do zero qualquer coisa eu ajudo tambem, eu tava vendo uns videos e achei legal a ideia de "como fazer um tema premium wordpress", do 0 ate coisas mais avancadas

**Comment by WendellAdriel** [comment]
Cara, sei que dei bobeira de não falar antes para entrar, mas sei que você manja muito de WP @cvalentefilho e eu sinceramente não gosto muito de WP, mas acho que foi pelos traumas que sofri quando comecei com PHP e com ele, eu era menos experiente e talz e aí não cheguei a me aprofundar no WP. Hoje vejo vocês falando de muitas coisas e parece ter mudado muito desde a época que peguei ele pra fazer alguma coisa. Teria como eu entrar no grupo para acompanhar essas paradas? Tenho muita experiência com PHP já (muita mesmo), experiência com outros CMS e talz, mas queria aprender sobre as novidades do WP, como está, etc e acho que você poderia ser um grande **mestre** para me ajudar hehehehhehe

**Comment by cvalentefilho** [comment]
Opa @WendellAdriel  demorou vou te add la no grupo do slack. 

Mestre, ainda não cara to aprendendo também.

mas sera de grande ajuda até pela sua experiência com PHP.

**Comment by cvalentefilho** [comment]
Esse link aqui será o nosso melhor amigo.

http://codex.wordpress.org/

**Comment by rafaDfaria** [comment]
Opa, isso muito me interessa, tenho um.site em wordpress, me inscrevendo como pupilo.

**Comment by williamcosta** [comment]
Opa galera!! Ainda tem vaga para esse grupo? Sei que estou meio atrasado... Já tenho um certa experiência com WordPress mas nada nível Master.

**Comment by LarissaAbreu** [comment]
Fala, @williamcosta. Tem sim cara! Entra no slack do CT aqui https://ctgroups.herokuapp.com/ (se você não estiver lá ainda) e agita a galera lá xD

**Comment by williamcosta** [comment]
Sim @LarissaAbreu já estou lá no slack do CT. Tenho que entrar em algum grupo privado?

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
