### ISSUE TITLE
Grupo de estudos ES2015

### ISSUE THREAD

**Issue by rogeralbinoi** [training-center/study-groups#39]
Formação de grupo para estudar Ecmascript2015

**Comment by WendellAdriel** [comment]
To dentro!!!! :wink:

**Comment by rogeralbinoi** [comment]
Demorou @WendellAdriel  ;)

**Comment by lucasbento** [comment]
Também to dentro :D

**Comment by LarissaAbreu** [comment]
Eu topo xD

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
