### ISSUE TITLE
2º Grupo PHP Undefined

### ISSUE THREAD

**Issue by LarissaAbreu** [training-center/study-groups#40]
2º Grupo de estudos de PHP (por favor, decidam um nome para que a gente possa criar um canal no slack pra vocês).

@fabricio1soares
@cvalentefilho
@diasEduardo
@andreamant
@roberthlima
@ValdirCamargo

**Comment by fabricio1soares** [comment]
Olá Larissa! Estou no outro grupo e já estou no Slack.
Abraços!

**Comment by WendellAdriel** [comment]
@cvalentefilho você que está como responsável desse grupo também por ser o mais experiente oks!?!?!?!??!

**Comment by WendellAdriel** [comment]
Vocês devem escolher um nome pra gente criar o canal do Slack pra vocês igual a @LarissaAbreu disse!!!! :wink:

**Comment by cvalentefilho** [comment]
Opa @WendellAdriel  pode deixar.

Nada de nome ainda?

**Comment by cvalentefilho** [comment]
Vou botar qualquer nome  nessa bagaça, ngm se manifesta

**Comment by diasEduardo** [comment]
chama de "Undefined" kkkkkkkkkk

**Comment by roberthlima** [comment]
cria logo com qualquer nome  @cvalentefilho

**Comment by cvalentefilho** [comment]
Boa @diasEduardo 

O nome vai ser Undefined

**Comment by cvalentefilho** [comment]
Criei o canal comi PHPUndefined no slack, deem um salve la para adicionar vcs

**Comment by cvalentefilho** [comment]
Agora pra iniciarmos.

Falem um pouco do nível de conhecimento em PHP de vocês.

.

**Comment by roberthlima** [comment]
cara adiciona logo a galera

**Comment by cvalentefilho** [comment]
Galera confirme os usários do slack por favor?

Abs

**Comment by roberthlima** [comment]
putz, adiciona logo todo mundo

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
