### ISSUE TITLE
Grupo SCRUM Masters (não confundir com a role SCRUM Master kkk)

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/study-groups#43]
Primeiro grupo para estudar SCRUM:

Eu
@MetalWingsWeb
@LarissaAbreu 
@davidasimoes
@Stoque
@alannaidon
@cvalentefilho

**Comment by WendellAdriel** [comment]
Canal criado e adicionei um pessoal lá já!!!! :wink:
@MetalWingsWeb vc está no Slack?!?!?!? se sim, qual seu user lá?!?!?!

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
