### ISSUE TITLE
Grupo Angular 2 HUB

### ISSUE THREAD

**Issue by LarissaAbreu** [training-center/study-groups#44]
Primeiro grupo para estudar Angular 2:

@WendellAdriel 
@marquinhusgoncalves
@LarissaAbreu
@GuimaP
@khaosdoctor

PS. Vou reforçar... Quem ainda não está no slack, por favor entrem :bowtie:

**Comment by khaosdoctor** [comment]
@LarissaAbreu o grupo do slack é o ctgroups? acho que eu já estou nele

**Comment by GuimaP** [comment]
Já estou no grupo :)

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
