### ISSUE TITLE
Brainstorm de Site para o CT

### ISSUE THREAD

**Issue by woliveiras** [training-center/study-groups#46]
Inicialmente não temos nenhuma ideia em mentes.

Pode liberar sua criatividade @baltazarparra.

Só precisamos de algo que tenha uma descrição sobre o CT (que temos aqui no Sobre) e os links para os repositórios, que são projetos do CT com a descrição deles.

Depois disso vamos tacar pau na codagem disso ae! ;D

**Comment by davidasimoes** [comment]
Faz um site estatico e hospeda aqui no GHB mesmo.

**Comment by jlamim** [comment]
Se precisarem de alguem pra dev front ou backend, contem comigo.

Em sábado, 9 de abril de 2016, David Simões <notifications@github.com>
escreveu:

> Faz um site estatico e hospeda aqui no GHB mesmo.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/training-center/sobre/issues/46#issuecomment-207836225>
>


-- 

*Jonathan Lamim Antunes*


*Desenvolvedor Web/Mobile & Palestrante*
*Tel: *+55 27 3082-4437 | 27 995 125 164

www.jlamim.com.br
www.github.com/jlamim
www.facebook.com/jlamim.projetos

**Comment by woliveiras** [comment]
Assim que definirmos tudo, poderemos tacar pau nesse repositório aqui: https://github.com/training-center/training-center.github.io

**Comment by baltazarparra** [comment]
Vamos começar pela arquitetura da informação? Se quiserem ir adiantando, vou dar uma saída agora e chego lá pras 20h.

**Comment by davidasimoes** [comment]
Que tal um modelo institucional : HOME, QUEM SOMOS, CONTATOS, e uma página para devilgar os grupos existentes.

**Comment by baltazarparra** [comment]
Acho que uma Onepage resolve, sem necessidade para outras páginas. @davidasimoes

**Comment by woliveiras** [comment]
Da pra juntar as duas ideias e ter uma onepage com aqueles links ancora para as sessões.

Possíveis sessões:

* sobre o projeto ou o que é o CT?
* grupos existentes
* como formar um grupo ou quero montar um grupo
* como entrar em um grupo ou quero entrar em um grupo
* informações úteis (não sei qual nome colocar, mas seria algo pra explicar como os grupos estão se comunicando, como eles se preparam pra estudar, dar dicas de estudos, dicas de organização, etc)

Depois poderíamos colocar um link pra "blog" e criar um blog com um Jekyll da vida pra galera que estiver estudando expor o que estão fazendo, como estão fazendo, postar dicas do que aprenderam, dificuldades que tiveram em algum ponto ou algo do tipo. Que tal? - Mas isso entraria em uma outra criação, poderia até ser com um tema simples do Jekyll Themes.

**Comment by baltazarparra** [comment]
Sessões:

- Centro de treinamento
- O que é
- Como funcionam os grupos
- Quer participar?

E dois links, um para o projeto Mentoria e um para o Blog CT.

Que tal?

**Comment by woliveiras** [comment]
Show! 

É interessante colocar uma sessão "nossos projetos" e falar sobre o Mentoria e o Blog nela?

Ai seria só um link pra descer até essa sessão e nela colocamos os links. O link pro Blog, deixamos com uns parenteses informando que sai em breve.

**Comment by baltazarparra** [comment]
Massa, ótima ideia, então ficamos com:

Sessões:
- Centro de treinamento
- O que é
- Como funcionam os grupos
- Quer participar?
- Nossos projetos

**Comment by woliveiras** [comment]
Fechou!

**Comment by danilovaz** [comment]
fala galera, passando pra me colocar a disposição se precisarem de algo em front :smile:

**Comment by baltazarparra** [comment]
Caras, to meio enrolado em um sprint, mas ainda essa semana sai o layout, sem falta.
Como vamos separar as camadas de desenvolvimento?

Fechar uma equipe e dividir as tarefas?

**Comment by woliveiras** [comment]
Sempre tem alguém disposto a ajudar num projeto desses mano. Relaxxxx. :smile: 

Um possível plano de ação:

Da pra divulgar nossa ideia de criar o projeto, compartilhando  [esse board do Trello](https://trello.com/b/0btLvDYP/site).

Ai fazemos o seguinte, para poder ficar claro e qualquer um conseguir prosseguir:

* Levantamos as tarefas que precisamos fazer
* Cadastramos tudo lá como cards, com o máximo de informações
* Qualquer pessoa que quiser ajudar, entra lá, solicita acesso ao board e pode pegar as tarefas e tacar pau.
* Depois é só abrir um PR no repositório do site

**Comment by baltazarparra** [comment]
A ideia do trello foi ótima, mas acho que seria legal alguém coordenar um pouco ao menos, pra manter um bom nível de código e organização. Ex. os interessados se manifestam para a área que gostariam de ajudar, e nos coordenaríamos as tarefas, passando as especificações para manter um bom código e não perder a sanidade.

**Comment by woliveiras** [comment]
Eu posso ajudar na Arquitetura de Front mano.

**Comment by woliveiras** [comment]
Tem o @jlamim que também tem um perfil desses e pode ajudar nessa gerencia. :D

**Comment by jlamim** [comment]
Estou a disposição pro que precisarem.

**Comment by idlua** [comment]
Seria ideal montar um boilerplate pra dar início a criação. Enquanto o @baltazarparra desenvolve um layout poderíamos ir definindo algumas tecnologias a serem usadas, como task runner, pré-processador CSS e etc.
Acho que uma estrutura básica dá conta e ainda daria chance de quem está iniciando ter contato com um ambiente de desenvolvimento real, e já começar a praticar.
Algo como **Gulp**, **Jade**, **Sass** ou **Stylus** e alguma estrutura modularizada pra organizar o CSS.

O que acham?

**Comment by woliveiras** [comment]
Boa mano

**Comment by baltazarparra** [comment]
@idlua perfeito mano.

Vou além, voto ainda por usarmos 'postcss' e forçar muito a questão de acessibilidade.

E usarmos o site como exemplo para futuros grupos.

**Comment by danilovaz** [comment]
cara, vi um projeto muito foda do[@willianjusten](https://github.com/willianjusten) que acho que podemos usar: [Qualy](https://github.com/Qualy-org/qualy)

**Comment by idlua** [comment]
@baltazarparra show! Bom que já começo a ler as documentações! Ainda não conheço muito bem tudo isso, sou um dos aprendizes! kkk
@danilovaz exato! Vi o Qualy do Willian no projeto do website de eventos do frontendbr.

**Comment by woliveiras** [comment]
Rapaz, é uma ideia bem boa usar o Qualy ein!

PostCSS acho mais embaçado, seria o mesmo que falar pra usar NPM Scripts mano @baltazarparra... A gente ve muito em posts na net, mas temos usado pouco em produção (no dia a dia). :(

Eu mesmo ainda nem tive o tempo legal pra estudar isso.

ES6 eu estou engatinhando por causa da correria por outras coisas. Ta OSSO. kkkkk

**Comment by baltazarparra** [comment]
Pode cre mano @woliveiras vamos alinhando, já está tomando forma as ideias.

**Comment by woliveiras** [comment]
Criar um para nossas necessidades, especificamente, acho uma boa.

Eu mesmo tenho o Kibe, mas sempre incentivo as pessoas a não usarem Generators, pois podem trazer muito mais do que vamos utilizar, do que conhecemos, etc. A não ser que seja o Generator perfeito pra necessidade ou que a pessoa não tenha tempo/não queira fazer.

**Comment by baltazarparra** [comment]
Sim, vamos reunir a galera que vai fazer o front, e pensar no que realmente vamos usar, ai criamos o nosso boilerplate, pra usar nos projetos do CT.

**Comment by woliveiras** [comment]
Show! :smile: 

Criamos uma issue para planejar a arquitetura?

**Comment by baltazarparra** [comment]
Acho que pode ser aqui mesmo, não?

**Comment by woliveiras** [comment]
Pode sim. 😄 

Vamos tacar pau!

## Estrutura de pastas e arquivos e nomenclatura do CSS:

Voto por utilizar **SMACSS** e, se possível **BEM**.

## Pre processador

Voto por **Sass** pelo material disponível e mais gente utilizando, apesar de eu ser fã de Stylus.

## Taskrunner:

Voto por **Gulp**, mas não reclamaria se alguém quiser usar **NPM Scripts**.

## Gerenciamento de dependências:

Como é coisa de Front, voto pelo **Bower** (creio que não precisamos criar algo que precise de Back End).

## ES6 ou ES5

Eu escolheria **ES5** por adicionar menos complexidade ao projeto, não acho que seria necessário utilizar ES6 e precisar de um Babel da vida, mas também não reclamaria de alguém querer usar ES6. :)

## Template Engines

Não tenho utilizado nenhuma, então não posso opinar, mas escolheria o **Jade** (ou Pug) por já ter estudado anteriormente.

## Framework/Lib JavaScript

Não vejo necessidade de utilizar Angular ou React, pois será algo razoavelmente simples.

## Suporte a navegadores

Opto, sempre, por não suportar o IE em todas as funcionalidades, porém fazer um Progressive Enhancement é bom pra não deixar as pessoas na mão.

## Sistema de Grids

Faz tempo que não utilizo nenhum, porém podemos usar, se acharem legal.

Existe um Framework legal com Grids com Flexbox, o [Bulma](http://bulma.io/), podemos pensar nele se quiserem.

**Comment by baltazarparra** [comment]
Acho que pra moldar o CSS, atomic design seria massa? Eu uso BEM no trampo, mas por falta de tempo, gostaria muito de estudar atomic design a fundo.

Também voto no sass pra pré-processador e acho que seria tentar montar as tasks direto pelo NPM, seria um puta aprendizado.

Sobre as dependências, não tenho uma opinião ainda, quais as vantagens de usar alguma ferramenta como o bower?

Js, acho que o ES5 mesmo, nosso javascript de baunilha dá conta de boas, por se tratar de um projeto sem muito complexidade.

Template Engines, também não tenho uma opinião pois conheço muito pouco, quais as vantagens?

E acho que não vamos precisar de mais nada, voto fortemente por fazer o css usando Flexbox no lugar de qualquer framework.

**Comment by idlua** [comment]
Também tenho a mesma dúvida do @baltazarparra sobre as dependências, até agora o .package.json gerado pelo NPM tem me servido bem em relação a isso, por isso ainda não vi muita coisa como Bower.
Só acho que seria melhor, @woliveiras, se for utilizado algum sistema de grid, optar pelo [Jeet](http://jeet.gs), excluindo a necessidade de inserir classes e mais classes no HTML.

@baltazarparra o Jade é uma mão na roda e nos ajudaria na organização. Templates engines podem ser considerados, a grosso modo, como os pré-processadores CSS. Você consegue escrever um código mais legível, modulado e a curva de aprendizado do Jade é mínima.

**Comment by baltazarparra** [comment]
Saquei @idlua 

Sou a favor de usarmos flexbox ao invés que qualquer sistema de grid.

**Comment by baltazarparra** [comment]
Vamos acrescentar mais algo?

![site_centro-de-treinamento_mobile_](https://cloud.githubusercontent.com/assets/7395304/14514085/d615454a-01c3-11e6-9996-a16f81f4d0cd.jpg)

**Comment by MetalWingsWeb** [comment]
Oi pessoal, estou com tudo complicado no trabalho, resolvendo diversas coisas ao mesmo tempo. Mas estou acompanhando toda noite e @baltazarparra curti bastante o design, por mim está aprovado!

**Comment by woliveiras** [comment]
@idlua e @baltazarparra, a grande vantagem do Bower em relação a usar o NPM seria poder escolher a pasta pra onde vão seus assets de Front.

A vantagem de utilizar um gerenciador de dependências é pra que não precise ficar entrando no site e baixando manualmente @baltazarparra, já que não commitamos o código de terceiros (libs) no nosso projeto diretamente.

Agora sobre o NPM como gerenciador de dependências Client Side (ou Front End) é mais questão de opinião pessoal com base nos estudos que fiz sobre o assunto (mas pode ser que eu esteja errado, me corrijam se eu deixei passar alguma coisa gente).

Imaginem que utilizamos alguma task de Bundle no `Gulp` (ou no NPM mesmo).

Para configurar essa task pra que concatene todos os arquivos de `libs` de Client Side de terceiros junto com os JS's de sua aplicação em um arquivo só, para mandar pra produção, demandaria mais esforço pra colocar uma por uma (libs) que estão em `node_modules` já que lá dentro é tudo junto e misturado, pacotes Node com libs de Front.

*Imagine a pasta do Express do lado da pasta do Angular ou jQuery.*

Se tivéssemos tudo numa pasta `js/assets`, ou `js/vendor`, ou qualquer outra que já eramos acostumados a fazer no nosso projeto Client, seria só colocar essa task pra ler tudo de dentro da pasta /js e mandar concatenar. *A única preocupação seria se algum arquivo tiver de vir antes do outro, porém ainda é mais simples.*

Ainda continuo com a opinião de ser contra usar o NPM pra gerenciar pacotes de Front por que não temos uma IDE pra facilitar nossa vida na hora de separar o que é pacote do Node e o que é pacote da aplicação Front End. Diferente do que acontece com o desenvolvimento Android, por exemplo, que é tudo feito via Gradle, mas o Gradle é auto gerenciável e as tasks de build são criadas pela própria IDE ou mesmo com o Go, onde colocamos um 'import' e a própria linguagem se encaminha de resolver as dependências e pensar no Build.

Quando é um modulo Node, é lógico que temos de usar o NPM, mas pra baixar o jQuery/Angular/Ember/Backbone/[outras libs de Front aqui] compensa deixar em `node_modules` ao invés de `js/assets` na aplicação Client Side e esquentar a cabeça pra criar a task de build?

**Comment by woliveiras** [comment]
@baltazarparra, o Layout está ficando supimpa! :smile:

**Comment by baltazarparra** [comment]
Vou trabalhar mais em cima dele, mas seria legal um feedback pra me ajudar a seguir pro lado certo.
...está meio cru ainda!
![site_centro-de-treinamento](https://cloud.githubusercontent.com/assets/7395304/14547258/3f0c2992-0282-11e6-87a9-ae7d36e52090.jpg)

**Comment by baltazarparra** [comment]
Preciso adicionar um pouco mais de interatividade com o github e desenhar a área 'nossos projetos' ainda.

**Comment by danilovaz** [comment]
@baltazarparra tá ficando massa. só não entendi o unicórnio kkkkkkkkkk

cara, eu curti, unica coisa que está bem estranho pra mim é o menu e o header.

talvez se trabalhar apenas com o logo, deixar o header somente na altura de um menu já que não há tanta informação mesmo e focar mais no conteúdo, mas tá ficando massa

**Comment by baltazarparra** [comment]
Obrigado pelo feedback @danilovaz 

Estou terminando de ajustar algumas coisas, e vou rever esse alinhamento que você citou.

**Comment by baltazarparra** [comment]
![site_centro-de-treinamento2](https://cloud.githubusercontent.com/assets/7395304/14577522/b489b576-034b-11e6-93ca-550691c9ac06.jpg)

**Comment by woliveiras** [comment]
WOW, ta ficando mais show ein mano @baltazarparra!

**Comment by baltazarparra** [comment]
Valeu mano @woliveiras =D

**Comment by baltazarparra** [comment]
Acho que é isso, vamos começar a trabalhar?

![site_centro-de-treinamento3](https://cloud.githubusercontent.com/assets/7395304/14587913/2df46518-0492-11e6-9f25-088990d92105.jpg)

**Comment by danilovaz** [comment]
@baltazarparra VAMOS!!!!!!!!!!!!!!!!!!!!!!! Volta aqui Balta :heart: , bora codar isso aí!

**Comment by woliveiras** [comment]
Vou criar uma issue no repositório do site pra começarmos os trabalhos, o que acham?

**Comment by danilovaz** [comment]
@woliveiras perfeito, podemos usar o know-how do site do [FrontEndBr](https://github.com/frontendbr/eventos/issues/3)

**Comment by baltazarparra** [comment]
Eita... e eu vou falar não? kkkk bora lá manos...  @danilovaz @woliveiras

**Comment by KarolinedeAlencar** [comment]
Oi galeere! Tudo bom? Sou meio que 'novata' mas adoraria ajudar ^^ Posso?

**Comment by woliveiras** [comment]
Boooooora @baltazarparra e @KarolinedeAlencar 

Colem nessa issue aqui: https://github.com/training-center/training-center.github.io/issues/1

Vamos discutir as tecnologias a serem utilizadas. 😄

**Comment by woliveiras** [comment]
Galera, como essa issue não está mais sendo atualizada irei encerrá-la.
