### ISSUE TITLE
Brainstorm - Material: Introdução ao Desenvolvimento Web

### ISSUE THREAD

**Issue by baltazarparra** [training-center/study-groups#48]
A ideia é criar um material sólido e recheado de boas práticas e casos reais,
para quem tem interesse em se aventurar no desenvolvimento Web.

Onde poderíamos formar grupos de futuros desenvolvedores,
pra auxiliar nesse primeiro contato com as bases do desenvolvimento, HTML e CSS.

**Comment by woliveiras** [comment]
Podemos subir no nosso repositório > https://github.com/training-center/materia

O @WendellAdriel já tinha uma ideia parecida ein

**Comment by danilovaz** [comment]
curti  a ideia.

mas seria algo como o [Guia para iniciantes](http://tableless.github.io/iniciantes/) do Tableless? ou seria algo com mais didática, examplos e try it yourself?

**Comment by woliveiras** [comment]
A ideia do @WendellAdriel seria como exercícios mesmo @danilovaz 

Ele não está respondendo aqui por que está numa correria lascada no serviço... Falei com ele mais cedo. kkkkk

**Comment by WendellAdriel** [comment]
Opa pessoal boa noite!!!!

Valeu mano @woliveiras, aqui está uma correria doida mesmo, mas dentro de uma ou duas semanas estarei mais ativo aqui no CT pra ajudar em tudo!!!

A ideia era fazer tipo um curso mesmo. Usaríamos arquivos `.md` que seriam divididos em três seções principais:

- **Introdução:** pequeno texto explicando um assunto específico com alguns exemplos e links de referência para estudo;
- **Exercícios:** exercícios para consolidar o que foi explicado na ***introdução***;
- **Desafio:** um desafio para aplicar o que foi aprendido até o momento (até mesmo de "aulas" anteriores) tentando utilizar situações comuns do dia-a-dia e exemplos reais;

E enquanto escrevia isso ainda tive outra ideia: no final do "curso" poderia juntar o(s) mentor(es) juntamente com os alunos e criar um e-book com o Gitbook pra liberar na comunidade!!! :wink:

O que acharam das ideias?

**Comment by woliveiras** [comment]
Show de bola cara.

Podemos fazer exercícios por capítulo e desafios práticos no final de cada abordagem (Ex.: Com os conhecimentos adquiridos até aqui, sobre HTML, crie uma página e valide no W3C + Alguma ferramenta de Acessibilidade. Poste o código + validação no repositório X).

**Comment by baltazarparra** [comment]
Caras, acho muito importante decidir o meio que vamos usar pra transmitir isso, eu voto fortemente por um Canal no youtube, bem simples, mas funcional, onde vamos dividir por playlist, HTML, CSS...
E lembrando que o foco são pessoas que nunca desenvolveram uma página na web.

Temos muitos cursos no youtube com conteúdo ruim, isso é péssimo pra um futuro desenvolvedor, ele já começa com uma base errada, eu gostaria de passar as melhores práticas e noções possíveis pra introduzir o desenvolvedor da forma correta, ajudando a criar uma próxima geração de desenvolvedores mais ativa.

**Comment by woliveiras** [comment]
Da pra juntar tudo isso mano.

O GitBook é uma página na Web, então o cara pode ver o vídeo durante a leitura. Ex.: [Vim para Noobs](woliveiras.com.br/vimparanoobs/)

Se comprometer a fazer vídeo é um pouco mais complicado, pois gravar, editar, subir, conferir... É um trabalho maior que nem todos vão conseguir ajudar. Então juntar as duas ideias seria da hora.

Dava pra fazer o GitBook e colocar alguns exemplos de criação no YouTube.

Ex.: Codificando o Layout X

Ai o cara ve como é o desenvolvimento de fato. Já sana algumas dúvidas que a galera sempre tem de: Como começo a codar, como planejar isso, como vou fazer algo escalável, etc.

**Comment by danilovaz** [comment]
concordo, vídeo demanda mais trabalho de produção. claro que, quem tiver tempo hábil para isso, é muito maneiro e fica realmente muito melhor para aprender.

acho que é como o @woliveiras falou, pode-se criar em um primeiro momento em forma de textos e os vídeos podem vir a complementar mais pra frente, já que com o conteúdo escrito pronto; o vídeo é um agregador de qualidade que pode ser incorporado depois.

**Comment by baltazarparra** [comment]
@danilovaz @woliveiras concordo com vocês, também nunca fiz vídeo, não tenho nenhum experiência com isso, mas realmente sinto falta de bons materiais nesse formato pra gente.

**Comment by WendellAdriel** [comment]
Podemos reunir diversas maneiras, mas realmente vídeo deve ser algo menos frequente pois dá um trabalho maior!!! O que podemos fazer também é sessões de **Live Coding** gravando com o Hangouts on Air e disponibilizar em um canal no Youtube.

Mas ainda sugiro que a forma principal seja por arquivos `.md` mesmo e depois sintetizar o conhecimento em um e-book criado com o **Gitbook**.

**Comment by woliveiras** [comment]
Demorou ein... Vamos fazer assim e ir adicionando interatividade de acordo com que der.

Vou propor uma organização de diretórios inicial pra gente começar a montar as "aulas".

**Comment by woliveiras** [comment]
Fiz uma estrutura básica de exemplo galera, validem a ideia se é uma boa:

https://github.com/training-center/materials/blob/master/README.md

Ai podemos escrever o material, ir colocando links para repositórios com o material (como o introdução do tableless) ou um bom conteúdo, mas devemos propor exercícios em cima disso.

**Comment by woliveiras** [comment]
Galera, como essa issue não está mais sendo atualizada irei encerrá-la.

Estamos tratando as melhorias do CT nessa issue: https://github.com/training-center/sobre/issues/6
