### ISSUE TITLE
Grupo MEAN Stack HUB

### ISSUE THREAD

**Issue by LarissaAbreu** [training-center/study-groups#49]
Primeiro grupo para estudar MEAN Stack:

@WendellAdriel 
@fauker
@LarissaAbreu
@marquinhusgoncalves
@heliomsolivas
@Cleysonlb

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
