### ISSUE TITLE
Organização dos grupos

### ISSUE THREAD

**Issue by idlua** [training-center/study-groups#50]
Pessoal, o projeto está tomando forma e precisamos nos organizar. Vários grupos já foram formados e alguns deles -- senão a maioria -- estão como cego perdido em meio a um tiroteio (sem saber pra onde correr).

##### Por quê?
O intuito inicial do projeto, idealizado pelo @woliveiras e o pessoal do FEMUG-ABC, era de abranger iniciantes no mundo do desenvolvimento. Aqueles que estão começando agora e que acreditam que HTML é uma linguagem de programação. *(não é, pessoal :b)*. Contudo, juntamente com os iniciantes, tem surgido muita gente com o intuito de aprender e também de ensinar, mas *já com uma carga de conhecimento*, e isso é muito bom! Mas em um grupo com os dois perfis há prejuízo no aprendizado: ou os iniciantes pulam vários passos básicos para acompanhar os assuntos discutidos, ou os mais avançados regridem para esperar os iniciantes, e então avançarem seus estudos. Por estes motivos alguns grupos estão estagnados.

Mas nos organizando as coisas irão fluir. Como poderíamos fazer isso? Tenho algumas sugestões.

## Mentores
A ideia de [Mentoria](https://github.com/training-center/mentoria) se encaixa perfeitamente com o intuito do projeto, e precisamos coloca-la em prática

##### Colocando isso em um exemplo prático para nós:
**1.** Um grupo de CSS é formado {**Grupo CSS Initial**} com um mentor que já conhece o básico de CSS, tendo assim, propriedade para mostrar o caminho a quem chegou agora;

**2.** Os 5~6 membros deste grupo aprendem a escrever CSS; então começam a estudar CSS3, Seletores especiais, criam alguns projetos de aprendizagem e etc., enquanto isso outros iniciantes chegaram e formaram um novo grupo {**Grupo CSS Learners**}. Quem poderia ser o mentor deste grupo? Algum membro do **CSS Initial**;

**3.** Um membro do CSS Initial começa então a ensinar ao **CSS Learners** o que aprendeu com o pessoal do seu grupo (Initial). *"Ensinar é aprender duas vezes. -- Joseph Joubert"*.

O mesmo acontece com os grupos mais avançados. Assim conseguimos abordar quem está iniciando e os que já conhecem algo, sem prejuízos, todos aprendem e tem oportunidade de ensinar; e os mais avançados voam juntos, abordando, obviamente, assuntos mais avançados. 

***
A maioria de nós dispõe de pouco tempo; trabalham, estudam, tem família.. e cada minuto é precioso. Formar grupos sabendo o que irão fazer; o que irão estudar, e focar nisso nos trará bom proveito desse tempo.

Para isso temos que começar a usar a área de [Mentoria](https://github.com/training-center/mentoria), enviando os 'formulários'. (Dando uma lida no README.me você vai entender rápido como funciona).

Precisamos também deixar bem claro nos formulários o que sabemos, para montarmos grupos de níveis iguais.

**Comment by woliveiras** [comment]
Boa mano, valeu por agitar!!! \o/

Só uma obs: O Mentoria não tem como objetivo ajudar Grupos de estudos viu... É um auxilio pra cada pessoa individualmente.

Os grupos podem pedir ajuda pra um Mentor, claro, mas esse não é obrigado a ajudar. A ideia de ambos os projetos é mais pra que o pessoal se auto-gerencie do que precise de um líder (por exemplo).

Os Mentores vão ajudar a planejar a carreira das pessoas, não planejar os grupos de estudos. Para isso tem um outro esquema crescendo, que até quem já tem bagagem pode ajudar que são os materiais de estudo: https://github.com/training-center/materials

Vou até dar uma atualizada nos READMES pra não confundir os projetos.

**Comment by woliveiras** [comment]
Atualizei pra ficar mais claro mano.

**Comment by idlua** [comment]
@woliveiras show! Acabei de ler os comentários na ISSUE de avaliação de mentores, e vim aqui reparar algumas coisas! Minha maior preocupação é mesmo em formar os grupos em níveis iguais. E pra discutirmos como fazermos isso. Em um grupo que estou, por exemplo, tem gente que não sabe nada ainda e tem quem já trabalha na área e tem grande experiência, daí o grupo está estagnado, sem saber como começar.

**Comment by WendellAdriel** [comment]
Essa parte que o @idlua disse é algo que pode ser pensada mesmo.

É sempre bom ter alguém com conhecimento maior para ajudar quem está iniciando, mas seria tipo um admin do grupo e o restante do pessoal ter o mesmo nível. E caso esse admin desse grupo queira aprender mais, tem que entrar em um grupo que vai ter um admin que sabe mais que ele que vai coordenar os estudos e outros membros do mesmo nível dele.

**Comment by woliveiras** [comment]
Hmm, aí é complicado mano @idlua, mas tipo: O ideal é que aproveitem o apoio dessa pessoa pra tirarem dúvidas, mas peguem materiais na net e taquem lenha estudar e transmitir conhecimento entre vocês.

É bem um estimulo pro lado cientista que temos desde crianças pra descobrir as coisas na base da pesquisa, experimentos, etc. Não esperem por um líder não. Juntem os materiais e taquem pau!

Somos todos cientistas, a sociedade que tira isso da gente impondo líderes pra tudo e acabamos perdendo essa nossa essência. :(

**Comment by woliveiras** [comment]
É maneiro também @WendellAdriel, mas a ideia inicial nem é ter admin de grupo mano. Só deve ter admin se acharem importante mesmo. De resto é experimentar e aprender sem compromisso com uma pessoa sabe?

Sem achar que precisa justificar o nível pra alguém, só estudarem juntos e praticarem juntos mesmo.

**Comment by woliveiras** [comment]
Eu tenho um artigo pra lançar essa semana sobre isso! kkkkk

Mas ainda preciso revisar alguns pontos pra não falar merda.

Talvez esclareça melhor o objetivo do CT.

Vou tentar deixar isso (sobre experimentar e sobre liderança) mais claro no README.

**Comment by WendellAdriel** [comment]
Massa mano @woliveiras por mim tanto faz asuhsauhsauhhua, eu to meio ausente, mas assim que ficar mais tranquilo volto e ajudo com oq eu souber nos grupos auhsuhsauhsaauhsauh

**Comment by woliveiras** [comment]
Isso ae mano @WendellAdriel!

@idlua vamos agitar esse povo nos grupos pelo Slack pra galera procurar experimentar mais.

Quem estiver ausente, da um toque pra pessoa, tira ela do grupo só pra não ficarem travados. É só deixarmos avisado que, depois, a pessoa pode entrar em outro grupo. Acho que ninguém vai ficar bravo por isso.

Se ficar, lascou! kkkk

Mas vamos ver no que da.

**Comment by idlua** [comment]
@woliveiras entendo, e é basicamente esse o ponto: não ter necessariamente um líder, citei mentor apenas como exemplo de alguém com mais experiência nortear iniciantes quando necessário. Mas o ideal é o grupo meter a cara na pesquisa e ir compartilhando com o grupo mesmo.

**Comment by woliveiras** [comment]
Aaa, show mano! 

Talvez, com os materiais que vão rolar ali, a galera consiga um norte nos estudos. 

Em todo caso, se acharem necessário, podem perguntar no canal geral do Slack que a gente tenta nortear também.

**Comment by woliveiras** [comment]
Dei uma melhorada na organização geral dos projetos, da uma olhadinha se ficou maneiro @idlua :D

**Comment by idlua** [comment]
@woliveiras muito show, mano! Tá bem claro como tudo funciona e acho até que já pode fechar essa issue aqui. :D

**Comment by woliveiras** [comment]
Aeeeee.

Agora sim mano! 

Qualquer problema é só dar um salve de novo e vamos tocar esse barco pra botar fogo nesse mundão do desenvolvimento!
