### ISSUE TITLE
Mudança de nome desse repositório

### ISSUE THREAD

**Issue by woliveiras** [training-center/study-groups#51]
Galera, o que acham de mudarmos o nome desse repositório para Study-Groups (para ser somente sobre os grupo de estudos) e criar outro "sobre" a organização?

**Comment by idlua** [comment]
Acho perfeito!

**Comment by WendellAdriel** [comment]
Muito bom!!!! :wink;

**Comment by woliveiras** [comment]
\o/

Já vou tacar lenha então!

**Comment by woliveiras** [comment]
Feito!
