### ISSUE TITLE
Grupo de estudos Flexbox + PostCSS

### ISSUE THREAD

**Issue by heliomsolivas** [training-center/study-groups#52]
Formação de um grupo para estudar Flexbox + PostCSS, a minha idéia inicial era refazer alguns sites conhecidos (e com código antigo) utilizando essas novas tecnologias, pra agregar conhecimento front-end + trabalho em grupo.

**Comment by woliveiras** [comment]
Eita, ai é sucesso ein @heliomsolivas 

Já convida a galera no nosso Slack.

**Comment by marcosabb** [comment]
To dentro!

**Comment by andersoonweb** [comment]
Tô querendo estudar também! Tô dentro :facepunch:

**Comment by leogoncalves** [comment]
To precisando estudar tbm.

**Comment by LarissaAbreu** [comment]
Que ideia show ein galera... Criei um canal (flexbox_postcss) lá no slack pra isso, bora estudar XD

**Comment by andersoonweb** [comment]
boa @LarissaAbreu ! Sugiro também que possamos fazer um hagount, algo onde podemos, conversar mesmo, acho que seria legal :smile:

**Comment by woliveiras** [comment]
Pode ser o assunto do primeiro Hangout ein @andersoonweb 😄 

Estamos marcando pelo Slack

**Comment by betodasilva** [comment]
Gostaria de participar também se não houver problema começar "do zero"...

Esse é um tópico aqui na minha 'checklist do que devo aprender', mas ainda não cheguei nele...e por isso preciso pegar um pouco de teoria com vídeo-aulas/tutoriais antes, pra ainda assim estar no nível newbie (sem experiência anterior)

Se não tiver problema, estou dentro.

Ps: Não tenho dificuldade pra aprendizado, mas fiquei com vontade de comentar porque entendi que o estilo de estudo é mais prático, não sei o nível de vocês :)

**Comment by raphaelmelo** [comment]
Se houver vaga, gostaria de participar!

**Comment by woliveiras** [comment]
Aeee, que sucesso! Venham pro Slack pra conversarmos lá sobre como vai funcionar que é sucesso galera.

**Comment by andersoonweb** [comment]
@woliveiras não seria melhor deixar aqui?

**Comment by heliomsolivas** [comment]
Pessoal quem quiser participar só colar lá no slack.

**Comment by woliveiras** [comment]
@andersoonweb pior que não cara. A galera é mais ativa no Slack.

Aqui estamos só pra unir o pessoal e depois eles vão pro Slack escolher como fazer tudo. :smile:

**Comment by andersoonweb** [comment]
Belezura @woliveiras ! Tô indo lá!!!

**Comment by woliveiras** [comment]
\o/

Sucesso mano! Agita esse povo lá.

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
