### ISSUE TITLE
Grupo de Estudos - English (#english channel)

### ISSUE THREAD

**Issue by metractive** [training-center/study-groups#56]
A issue tem o propósito de organizar o primeiro grupo de discussão semanal em inglês e talvez os próximos pra não rolar um spam de issues 😄 

A ideia é cada semana pegarmos um dia da semana para realizar uma apresentação breve de todos em um Hangout, onde cada um deve conversar sempre em inglês sobre algum assunto de tecnologia. Esse assunto será definido antes da conferência, logo, é interessante que todos estejam afim de comentar, opinar ou compartilhar conhecimentos em inglês.

Sabemos que um dos piores medos é a vergonha de falar errado, mas lembrem-se que estão todos no mesmo barco.

Caso queiram interagir sobre esse assunto no slack do *ctgroups*, ele está presente no channel #english. Penso que pode ser interessante criar um channel privado para cada semana? Assim sabemos quantas pessoas vão participar.

Algumas perguntas que queria levantar aqui:
- Acham que deve existir um limite de pessoas por conversa semanal?
- Se tiver, vamos fazer um rotativo, assim cada vez mais pessoas podem conversar?
- Acham interessante esse tipo de conversa ocorrer em um MeetUp?
(onde todos precisam falar em inglês 😆 )

O assunto que foi levantado como o primeiro tópico pelo @francofrancisco, é relacionado a tecnologia IoT. O que acham?

Caso queiram falar comigo no slack, estou como @marcelo-mw :)

**Comment by frenktico** [comment]
YQY (Yaaas Queen Yaaas)

**Acham que deve existir um limite de pessoas por conversa semanal?**
Não.
**Se tiver, vamos fazer um rotativo, assim cada vez mais pessoas podem conversar?**
Seguindo a resposta anterior, quanto mais gente melhor, há quem goste de ler/acompanhar e também os que vão interagir.
**Acham interessante esse tipo de conversa ocorrer em um MeetUp?**
É válido, curto a ideia e faz com que geral possa trabalhar a escuta e pronúncia também. ;)

**Comment by metractive** [comment]
Show @frenktico, valeu pelo feedback. Me deu até ideias, já que apresentações em inglês podem ajudar o pessoal a se preparar para um futuro, onde tenham de fazer apresentações em inglês sobre tecnologias, entre outros.

**Comment by woliveiras** [comment]
Ai sim @metractive 

Vamos agitar isso ae!

**Comment by frenktico** [comment]
Posso dar help no vídeo ou podcast se for o caso.

Em 5 de mai de 2017 07:37, "William Oliveira" <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
\o/

Aiiii siiiim @frenktico

**Comment by marioernestoms** [comment]
Gostaria de participar também, já falo inglês mas é sempre bom ter um grupo pra ficar exercitando. ainda falando sobre TI que adoramos fica mais legal ainda.

**Comment by metractive** [comment]
Show @marioernestoms. To pra organizar uma data pro Hangout, ai aviso todos que estiverem interessados por aqui. Envio mensagem para vocês pelo slack direitinho :smile:. Mas ainda fico no aguardo de novas interações por aqui.

**Comment by danilosilvadev** [comment]
Gostaria de participar tbm se ainda tiver vaga.

**Comment by hader-araujo** [comment]
Ainda fazem os encontros?

**Comment by woliveiras** [comment]
Rolam hangouts direto, @hader-araujo 

Chega junto no nosso slack, no canal #english

**Comment by danilosilvadev** [comment]
Pode ser no discord um dia n?

**Comment by hader-araujo** [comment]
@woliveiras obrigado, entrei lá. Vi que tem o canal geral e apresentações. Vou procurar o de inglês. Valeu

**Comment by woliveiras** [comment]
Galera, como o grupo já existe no slack e estamos divulgando ele sempre, vou fechar essa issue aqui.

Qualquer coisa me avisem que podemos reabrir. :)
