### ISSUE TITLE
Grupo de estudos - React

### ISSUE THREAD

**Issue by YuriBrunetto** [training-center/study-groups#57]
Recrutando devs para formarmos um grupo de estudo sobre React. 

Iremos definir conteúdos para estudar, fazer hangouts para discutirmos o que aprendemos, etc. Gostaria de ter pelo menos uma pessoa no grupo que realmente entenda sobre React para de vez em quando nos dar até uma pequena mentoria nos conteúdos (também ajudando com boas práticas e apontando erros comuns).

Um abraço para todos. 😄

**Comment by woliveiras** [comment]
Eu topo!

Não serei o cara que manja de React, mas quero entrar para aprender. 😄

**Comment by metractive** [comment]
Também to afim de entrar pra aprender :)

**Comment by alinebastos** [comment]
Opa, tô dentro pra apdender tb o/

**Comment by adeonir** [comment]
Oi? Aprender? Sim... eu quero!

**Comment by marioernestoms** [comment]
Opa, to dentro só que pra aprender também. :)

**Comment by YuriBrunetto** [comment]
Vamos começar com "exercícios" então! Vamos vendo o que cada um já sabe sobre o framework e depois disso vamos vendo se alguém mais experiente se interesse pelo grupo 💃 

Amanhã falo com o @woliveiras para criarmos o channel no nosso Slack! 😄

**Comment by YuriBrunetto** [comment]
@metractive tu tá no Slack do CT? Se sim, como que tá teu user lá?

**Comment by metractive** [comment]
Sim! @marcelo-mw

**Comment by leonardocintra-luizalabs** [comment]
Galera eu fiz uma app para brincar e aprender
Segue com React Puro (sem redux)
https://github.com/leonardocintra/lista-de-tarefas-reactjs/tree/react-puro-sem-redux

Mesma app com o Redux
https://github.com/leonardocintra/lista-de-tarefas-reactjs/tree/master

**Comment by peofernandes** [comment]
QUERO APRENDER!!!!

**Comment by fdaciuk** [comment]
Fala galera! Ótima iniciativa! Se precisarem, posso ajudar dando algumas direções de conteúdo a estudar =)

**Comment by brunopulis** [comment]
Eu topo, porque não!?

**Comment by aryrabelo** [comment]
Entrando pra aprender, focado em ReactNative!!

**Comment by lflimeira** [comment]
Eu topo tbm, estou estudando no momento, no que eu puder ajudar estou a disposição, mas estou mais para aprender.

**Comment by Gabrielbdd** [comment]
Aprendizado? Estou dentro hahaha

**Comment by YuriBrunetto** [comment]
@fdaciuk excelente, brother! Passa teu user no Slack que te adiciono no channel 😄  🤘

**Comment by fdaciuk** [comment]
@YuriBrunetto é `@fdaciuk` mesmo xD

**Comment by gabrielcraveiro** [comment]
Eu também toparia

**Comment by lucasmarques73** [comment]
To dentrro :v:

**Comment by guilhermedeoliveira** [comment]
Também estou estudando React. Gostaria de participar!

**Comment by cantoniazzi** [comment]
Estou dentro também! :+1:

**Comment by woliveiras** [comment]
\o/

Tem um canal #react-studies no nosso Slack galera, entrem lá, pois já está rolando troca de XP. :D

**Comment by woliveiras** [comment]
Galera, como o grupo já existe no slack e estamos divulgando ele sempre, vou fechar essa issue aqui.

Qualquer coisa me avisem que podemos reabrir. :)
