### ISSUE TITLE
Grupo de estudos- JavaScript

### ISSUE THREAD

**Issue by richmanzoli** [training-center/study-groups#58]
Eai Devs de todo brasil 👍 

Estou aqui para recrutar pessoas que queiram estudar JS (ES5).
O intuito desse grupo de estudo é estudar/praticar JS, muita gente como eu sabe o basico de JS mas nunca usou em algum projeto.

A minha ideia é inicial é decidir um projeto a ser feito com JS e claro ter um Ninja JS para nos auxiliar com duvidas. (caso alguem se disponibilize, claro.)
Podemos marcar datas/horarios pra conversamos sobre, usando o Hangouts.

Bom, estou aberto a sugestões, caso alguem queira falar comigo, só mandar aqui na Issue ou me mandar uma mensagem no slack, um abraço! 💛

**Comment by alinebastos** [comment]
Quero! o/

**Comment by istiu** [comment]
To precisando! 😁 
Mas pra participar precisa estar como pupilo de alguém ou é aberto a todos?

**Comment by leanfj** [comment]
Tbm to precisando. Tenho a mesma dúvida @istiu

**Comment by alinebastos** [comment]
Seria legal um canal lá no Slack pra esse grupo de estudos, pra nos organizarmos, da mesma forma que existe o grupo de estudos de react, né?

**Comment by cotts** [comment]
To dentro.

**Comment by alinebastos** [comment]
Acredito que seja pra todos interessados em estudar javascript :)

**Comment by richmanzoli** [comment]
é para todos interessados em estudar JS, nada de mentor/pupilo, apenas um grupo de estudos pra quem quer estudar/praticar JS 🤓 

Já falei com o William e agora to esperando a aprovação dele, assim que estiver aprovado ele vai criar um grupo no Slack para discutimos sobre.

**Comment by leanfj** [comment]
@richmanzoli Poderíamos fazer alguma coisa para nivelar o conhecimento da galera, pros estudos partirem de um ponto? Tipo uma bibliografia básica ou algum curso online tipo codecademy/Parte JS do FCC.

**Comment by alinebastos** [comment]
Pois é, minha opinião, acho que a pessoa tendo um curso básico de JS (tipo do FreeCodeCamp, Codecademy, etc) já tá apta, o que vcs acham?

**Comment by istiu** [comment]
Fiquei com essa mesma dúvida do nivelamento também, mas como a @alinebastos disse, acho que com o básico, a gente consegue até um ir ajudando o outro pra que todos se estabilizem no mesmo nível.

**Comment by leanfj** [comment]
Show @alinebastos Isso mesmo. Digo mais para direcionar um iniciante do que ser uma condição para estudar/acompanhar os estudos no grupo. No meu caso fiquei muito perdido com o que estudar até encontrar o "caminho e a verdade" rsrs

**Comment by brunorafael8** [comment]
quero também

**Comment by alinebastos** [comment]
Ah sim, não iremos excluir ninguém, se alguém quiser acompanhar o grupo enquanto aprende o básico em algum site, é super bem vindo :)

**Comment by richmanzoli** [comment]
Show!!! seria otimo, será que existe algum teste basico? ou poderia ser criado tambem.

Poderia ser feito tambem partes do projeto, Iniciante/Intermediario/Avançado e claro, todos participando juntos, o iniciante pode acompanhar o Intermediario para ter uma noção do que pode ser feito.

Ou tambem existir mais de um projeto, algo basico e um mais avançado, mandem mais sugestões 😄

**Comment by ronalson** [comment]
Opa! Gostei muito do que li até aqui. Quero muito participar do grupo.

Se me permitem, gostaria de dar uma sugestão para a dinâmica do grupo num primeiro momento:

**Passo 1: Lista de projetos** 
Mentores e/ou desenvolvedores com mais experiências fariam propostas de pequenos projetos práticos, nos quais eles sabem que é importante utilizarmos alguns conceitos fundamentais do Javascript (closure, classes, scopping, mv* etc). Com essa lista em mão faríamos uma votação para escolher a ordem de implementação.

Para começar pode ser uma lista pequena, com 5 projetos, e cada um deverá ter:

- Descrição do projeto
- Conceito chave
- Referências (textos ou vídeos)
- Exemplos (não precisa ser liberado no mesmo dia do projeto)

**Passo 2: Coding**
Cada participante trabalharia na sua própria solução e subiria para algum repositório ou codepen. Durante o período de coding trocaremos ideias e experiências no slack.

**Passo 3: Liveconding ou Blog**
Finalizado o período de trabalho, teríamos uma live ou blog com os mentores abordanto o projeto e discutindo o conceito chave.

---

Acredito que essa estrutura seria uma boa maneira de alinharmos teoria com prática. Além disso, pode ser um bom ponto de partida para todos os níveis, uma vez que ficará bem claro o que é para fazer e que caminho seria interessante seguir na solução dos problemas.

No futuro, conforme o grupo for avançando, podemos pensar em outros formas de levantar projetos dentro do grupo. Mas o legal é que teremos uma base / catálogo de projetos para quem começar mais adiante.


Estou sugerindo isso sob o meu ponto de vista de iniciante, caso a expectativa de vocês seja algo menos fundamentado em teoria, estou dentro também.

**Comment by richmanzoli** [comment]
Gostei muito da sugestão, achei bem interessante a forma de separar as etapas entre Lista de Projetos/Coding/Live Coding.

Acho que a unica coisa que não ficaria legal é focar em Mentores, nesse grupo seria chamados apenas de Devs, porque creio que Mentores tem uma lista fixa de pupilos e aqui no grupo de estudo vai entrar gente sempre que puder, então acho mais valido ter sim alguem com um bom conhecimento em JS, mas não precisa ser um mentor, apenas Dev "FODÃO" em JS 😄 

Mas foi uma otima sugestão, muito melhor ter algo bem organizado, como passou.

**Comment by woliveiras** [comment]
Muito boa @richmanzoli!

Na nossa comunidade não precisa pedir permissão não mano.

Você falou que ia fazer, tá feito!

A comunidade é **nossa**: quando vocês querem fazer algo que beneficia a todos, então é feito! 😄

**Comment by woliveiras** [comment]
A ideia do @ronalson é muito boa galera!

Se vocês quiserem, eu posso ajudar nessa pegada, pois estou precisando melhorar mais meu nível de JS puro; então uma coisa puxaria a outra. 😂

**Comment by woliveiras** [comment]
Criei o canal javascript-studies, lá no Slack galera!

Bora pra lá. :D

**Comment by ronalson** [comment]
Massa! Vamos que vamos!

@richmanzoli concondo 100% contigo, o grupo não deve focar em mentores. Minha sugestão de chamar mentores e/ou devs experientes foi apenas para um primeiro momento. No caso, seria uma ajuda para montar essa lista de projetos iniciais, com foco em questões fundamentais do JS. Seria algo mais pensado para dar um norte ao grupo nas primeiras iterações. 

@woliveiras você acha que consegue ajudar nesse levantamento de projetos? Outra coisa, dei a sugestão do **passo 3** - livecoding e posts - pensando nas coisas que a comunidade já realiza: as lives e o formulário com pedido de posts. Você acredita que essas coisas podem ser mescladas com as demandas do grupo?

---

Você preferem discutir esses pormenores por aqui ou fica melhor no Slack? Podemos marcar um dia para debater os detalhes de funcionamento: a. aonde serão publicados os projetos?; b. qual o período de trabalho?; c. plataformas de publicação dos trabalhos? e coisas do tipo.

**Comment by KarolinedeAlencar** [comment]
Oláa! Posso participar tb?

**Comment by richmanzoli** [comment]
Pessoal o William criou o grupo no slack, vamos levar essa conversa pra lá, porque fica mais facil a comunicação de todos!

@KarolinedeAlencar pode sim e todo mundo que quiser participar é só chegar junto com a gente 🦅

**Comment by woliveiras** [comment]
Acho super válido a criação de posts com os avanços do grupo!

Livecode então... Super apóio, @ronalson 

Suas ideias foram muito boas pra esse grupo. Vamos tocar fogo nisso pra fazer acontecer. 🙌

**Comment by kellfluz** [comment]
Pessoal boa tarde!
Tô querendo entrar nesse grupo ai, mas to perdida no Slack, procurei o grupo javascript-studies mas aparece "We couldn’t find your team". Alguém pode me ajudar? =(

**Comment by alinebastos** [comment]
@kellfluz te invitei pro canal :)

**Comment by kellfluz** [comment]
Ahhh obrigada @alinebastos, já aceitei <3

**Comment by celosotomaior** [comment]
Tenho interesse em participar!

**Comment by sergiobonifaciojr** [comment]
Quero participar, por favor.

**Comment by brenobo** [comment]
Opa, gostaria de participar.

**Comment by juulhao** [comment]
Comoo participaar???? *-*

**Comment by woliveiras** [comment]
Fala, galera! Podem entrar no nosso slack, no canal #javascript-studyes

https://github.com/training-center/slack

**Comment by woliveiras** [comment]
Galera, como o grupo já existe no slack e estamos divulgando ele sempre, vou fechar essa issue aqui.

Qualquer coisa me avisem que podemos reabrir. :)

**Comment by henriquedomanski** [comment]
Não to conseguindo entrar. ta dando "Failed! invite_limit_reached" :(

**Comment by AnaPaula-Morais** [comment]
Olá pessoal. Estou começando a estudar javascript e procurando um grupo pra estudar e debater sobre o tema achei vcs. Como faço para entrar no grupo?
Muito boa a iniciativa :)

**Comment by karolinedealencar** [comment]
> Olá pessoal. Estou começando a estudar javascript e procurando um grupo pra estudar e debater sobre o tema achei vcs. Como faço para entrar no grupo? Muito boa a iniciativa :)

@AnaPaula-Morais, acho que o grupo de study não existe mais. Conseguiu achar/entrar?

**Comment by sergiobonifaciojr** [comment]
Este grupo é de 2017, se eu não me engano. Acredito que foi descontinuado.

Em seg, 25 de abr de 2022 19:37, Karoline Alencar✨ ***@***.***>
escreveu:

**Comment by AnaPaula-Morais** [comment]
@karolinedealencar Não consegui nem entrar nem achar hahaha
Acho que realmente não deva mais existir. 
Vc conhece outro grupo de javascrip ou frontend?

**Comment by karolinedealencar** [comment]
> AnaPaula



> @karolinedealencar Não consegui nem entrar nem achar hahaha Acho que realmente não deva mais existir. Vc conhece outro grupo de javascrip ou frontend?

@AnaPaula-Morais Puts, não conheço nenhum grupo fechado, mas a @pachicodes tem um grupo no discord que tem uma aba de grupo de estudos/ajuda! https://discord.gg/g69zHbUM

**Comment by AnaPaula-Morais** [comment]
@karolinedealencar obrigada pela dica vou dar uma olhada!!

**Comment by sergiobonifaciojr** [comment]
Há bastante tempo que eu não programo. Pra ser exato, 4 anos e 3 meses.
Estou começando a voltar agora, logo não consigo lhe informar com precisão
onde tem. Meu conselho é você estudar pelo youtube, por enquanto.

**Comment by NicolasBaraldodeLima** [comment]
Tenho interesse em participar.

**Comment by karolinedealencar** [comment]
> Tenho interesse em participar.

@NicolasBaraldodeLima Oi Nicolas, o grupo de estudo não existe mais mas da uma olhada nesse comentário:

https://github.com/training-center/study-groups/issues/58#issuecomment-1109773703
