### ISSUE TITLE
Grupo de estudos - Vue.js 2.x

### ISSUE THREAD

**Issue by heliomsolivas** [training-center/study-groups#61]
Fala pessoal, tive a experiência de pegar um projetinho grande e não foi feito com framework front nenhum (tem muito js) e estou tentando pegar firme no Vue.js 2 para resolver os problemas que tive nesse projeto (somente para estudo), caso alguém tenha interesse é só comentar aqui. 
Obs: sou bem iniciante com ele mas tenho estudado todo dia. valeu :)

**Comment by woliveiras** [comment]
\o/

Já compartilhou essa issue no nosso slack, @heliomsolivas?

**Comment by heliomsolivas** [comment]
@woliveiras , acabei esquecendo mas vou compartilhar!

**Comment by brunorafael8** [comment]
Já tenho um boa experiência com Vue, se precisar de ajudar, só falar comigo no slack

**Comment by leonantvrs** [comment]
também estou estudando vuejs @heliomsolivas, se eu poder ajudar em alguma coisa só chamar.

**Comment by heliomsolivas** [comment]
@brunorafael8 vou te chamar no slack qualquer hora,
@leonantvrs da uma olhada nesse repo https://github.com/heliomsolivas/vue-estudos , qualquer ajuda é bem vinda, até na parte teórica

**Comment by woliveiras** [comment]
Se estiver rolando e precisarem criar um canal no Slack é só falar comigo lá, viu galera. :D

**Comment by woliveiras** [comment]
Galera, estou fechando o repositório para que vocês se comuniquem no Slack. 

Qualquer problema é só chamar a moderação lá, viu.
