### ISSUE TITLE
Grupo de estudos- PHP e POO

### ISSUE THREAD

**Issue by richmanzoli** [training-center/study-groups#62]
Boa noite Developers 💯 

Estou aqui para recrutar pessoas que queiram estudar PHP Puro (SEM FRAMEWORK) e POO com PHP
O intuito desse grupo de estudo é estudar/praticar PHP e POO, muita gente como eu sabe o basico de PHP mas nunca usou em algum projeto pessoal.

Bom, eu criei o grupo de estudos JS e vejo o pessoal discutindo bastante lá no channel e vi que deu certo, porém mesmo eu tendo MUITO interesse em JS, hoje eu estou trabalhando em PHP e Laravel e preciso muito estudar a fundo PHP e não tem maneira melhor que estudar junto, pelo menos eu gosto.

Bom, estou aberto a sugestões, caso alguem queira falar comigo, só mandar aqui na Issue ou me mandar uma mensagem no slack, um abraço! 💛

**Comment by woliveiras** [comment]
:+1:

**Comment by wandersonmaceds** [comment]
Opa @richmanzoli acho a ideia pra lá de bacana, tenho alguma experiência com PHP mas não sou nenhum mestre ou coisa do tipo. Gostaria de contribuir com você nessa jornada. 

Tem alguma ideia de como funcionaria esse grupo de estudos?

Já faz um tempo que não apareço lá no slack, mas retornarei e estarei disponível por lá também caso queira conversar.

**Comment by davidallysson** [comment]
Suuuper topo participar!

**Comment by richmanzoli** [comment]
Que bom que apareceu interessados, então primeiro vamos ter que falar com o @woliveiras para criar o chanel lá no Slack, então bora começar acessar a comunidade por lá em :)

Creio que seria legal compartilhar experiencias, dicas de estudos e claro o mais importante, criarmos um projeto no qual todos podem contribuir.

Estou aberto a ideias, quem quiser só postar aqui ou me chamar no Slack, para planejarmos tudo!

**Comment by yagoananiasbr** [comment]
Tenho interesse! :)

**Comment by wilkergaudencio** [comment]
Tenho Interesse tbm!

**Comment by davidallysson** [comment]
Que tal usarmos um livro-base? Vou começar a ler o PHP - Programando com Orientação a Objetos do Pablo Dall'Oglio hj.

**Comment by richmanzoli** [comment]
@davidallysson estou bastante interessado nesse livro, mas não conheco alguem ainda que tenha lido ele, pode ser uma boa ideia!

Ainda estou no aguarde do @woliveiras criar o grupo, assim que criar, vamos pro Slack discutir isso e começar o quanto antes!

**Comment by woliveiras** [comment]
Opa, desculpe a demora, @richmanzoli 

Criei lá no slack! #php-studies

**Comment by bedgerotto** [comment]
Opa! Bora estudar PHP!

_Sent from my Lenovo A6020l36 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by raonibz** [comment]
Poderiam por um pedacinho de MVC !? :)

**Comment by llmdev** [comment]
Tamo Junto!
Bora Melhorar Habilidades Jedi no PHP (Ganha pão de muitos rsrs) ;D

**Comment by alannaidon** [comment]
MVC e Boas práticas <3

**Comment by gabriela-castro** [comment]
Adorei a ideia! Eu trabalho com PHP há quase 4 anos e estou mesmo buscando me reciclar. Vamos estudar juntos então.

**Comment by richmanzoli** [comment]
Galera, quem tiver interessado ja estamos com o channel criado no Slack :)

So baixar o Slack, entrar no grupo do Training Center e ir pro grupo #php-studies !

**Comment by Diego-Brocanelli** [comment]
Excelente ideia, eu topo!

**Comment by woliveiras** [comment]
\o/

Ai vocês estarão em boas mãos! 

@Diego-Brocanelli vai ensinar muito nesse grupo!

**Comment by woliveiras** [comment]
Galera, visto que já estão se organizando pelo Slack, podemos fechar essa issue?

**Comment by Diego-Brocanelli** [comment]
Acredito que sem problemas encerrar @woliveiras

**Comment by richmanzoli** [comment]
Pode encerrar sim, já estamos com tudo feito no slack! valeu @woliveiras

**Comment by woliveiras** [comment]
:metal: :metal: :metal:
