### ISSUE TITLE
Criação de um repositório para o Grupo de Estudos PHP/POO

### ISSUE THREAD

**Issue by Diego-Brocanelli** [training-center/study-groups#63]
Olá, Pessoal.

Demos início com o grupo de estudos de PHP/POO no Slack (php-studies).

Com isso achamos interessante criarmos um repositório focado ao grupo de estudo, para que assim possamos:

- Centralizar as informações.
- Registrar as pautas das reuniões.
- Armazenar todo o conhecimento gerados pelo grupo.
- Armazenar material de apoio para os estudos.

Porém, para que isso seja feito devemos analisar se é do interesse do grupo em criar e principalmente manter o repositório, para que assim o mesmo não fique abandonado sem manutenção.

Peço a todos que deixem sua opinião para que possamos analisar esta possibilidade.

Para termos uma ideia nosso colega [Richard Manzoli criou um repositório](https://github.com/richmanzoli/Grupo-de-Estudos-PHP-POO) que estamos inserindo o conteúdo nele, e está ficando bem bacana :)

Particularmente acho fantástico criarmos um repositório dentro do Training Center pois assim enriquecemos nossa comunidade.

**Comment by mayronceccon** [comment]
O repositório seria a melhor forma de centralizar as discussões/conhecimentos, assim novos membros do CT poderão acompanhar o que já foi feito.

**Comment by jkhaesar** [comment]
Concordo, facilita aos novos membros acesso ao material e também aos mentores/pupilos que podem acrescentar/utilizar o conteúdo para os estudos na mentoria.

**Comment by osmar-vil** [comment]
Criar uma RoadMap de estudos também sería uma ótima idea, para iniciantes, intermediarios e profisionais da área.

tipo um guía completo (ou pelo menos uma tentativa)

**Comment by Diego-Brocanelli** [comment]
Acho válida a sua ideia @osmar-vil podemos criar uma estrutura para mapear as áreas de conhecimento e dividir em níveis para melhor aproveitamento.

Estamos no processo de definição (data, hora e plataforma) para nossas reuniões. Após o termino desse processo vamos focar no material de estudo.

O importante é manter o foco do grupo e manter os dados do RoadMap dentro dos objetivos (PHP/POO).

:)

**Comment by Jovsantos** [comment]
Achei show essa ideia do repositório, até por que todos que estão aprendendo seja iniciante ou não procuram um norte nesse mar de informações, organizar os estudos e os melhores cursos, artigos e tutoriais vai poupar um tempo de pesquisa enorme.

**Comment by woliveiras** [comment]
Acho bem legal criarmos um repositório para o grupo de estudos de PHP. Porém os grupos podem ir crescendo e precisando de mais repositórios, nesses casos criaríamos mais repos depois ou centralizaríamos tudo em um repositório grandão do php-study-groups.

Acho maneiro adicionar o repo aqui por conta do que vocês estão falando: centralizar e mostrar pra outras pessoas como podem fazer.

Vou levar essa issue para o restante da comunidade para discutirmos.

**Comment by Diego-Brocanelli** [comment]
@woliveiras então vamos aguardar a análise do restante da comunidade antes de fecharmos :)

**Comment by woliveiras** [comment]
Vou levar isso pro slack pra começar a trocação de soco lá, mano! :metal:

**Comment by angelilton** [comment]
levando em consideração será em formato de um curso acho valido criar o repo vinculado ao CT

**Comment by Diego-Brocanelli** [comment]
@woliveiras acho que podemos fechar essa issue e focarmos na que vc criou https://github.com/training-center/study-groups/issues/66  posso fechar a isseu?

**Comment by woliveiras** [comment]
Opa, perfeito, @Diego-Brocanelli
