### ISSUE TITLE
Reestruturar a dinâmica dos grupos de estudos

### ISSUE THREAD

**Issue by woliveiras** [training-center/study-groups#65]
A maneira como temos o projeto hoje é bem aberta e sujeita a falhas por conta da falta de acompanhamento dos grupos.

## Como aberta?

Não demos um guia de como as pessoas podem montar seus grupos, como se comunicar ou algo do tipo. Deixamos tudo livre, porém as pessoas precisam de algum direcionamento para que os grupos funcionem.

## Que tipo de falhas podem acontecer no atual modelo?

- uma issue pode ficar aberta esperando membros para sempre
- os grupos podem começar animados e depois de algum tempo morrer por falta de direcionamento
- os grupos podem ficar perdidos no que estudar

## Do que precisamos

- precisamos de um modelo novo, onde teremos uma pessoa responsável pelo grupo.
- precisamos de alguém com XP no assunto a ser tratado pelo grupo de estudos para lhes guiar, podendo ser a mesma pessoa responsável pelo grupo ou não

A pessoa responsável pelo grupo cuidará de toda a comunicação entre participantes, de marcar reuniões, montar um time para lhe ajudar a organizar tudo e ficar de olho nas issues direcionadas a ela.

A pessoa com mais experiência irá transmitir seu conhecimento para o grupo de estudos através de pequenos direcionamentos e resposta a pequenas dúvidas.

**Comment by woliveiras** [comment]
Possível sugestão de modelo:

- a pessoa descobre nosso projeto
- abre uma issue para reunir pessoas
- divulga essa issue no nosso Slack e de lá nós divulgamos em outros meios de comunicação
- a pessoa é responsável por montar um time com, ao menos, uma pessoa com experiência no que desejam estudar e outros membros para o corpo do grupo
- essas pessoas, unidas, serão responsáveis por seus repositórios (projetos que criarem)
- essas pessoas podem usar o Slack com um canal nomeado por elas para se comunicarem e não confundirem outros grupos do mesmo assunto (pode estar rolando dois grupos de estudos de PHP, por exemplo)

**Comment by ronalson** [comment]
Como eu acho que pode funcionar a estrutura de repositórios dos grupos de estudos:

1. O repo /study-groups deve manter um index de todos os grupos de estudos ativos.

2. Cada grupo tera o seu próprio index (repositório). 
- O nome do repo deve seguir um padrão para todos os grupos: "/sg-php", "/sg-vanillajs", "/sg-vuejs"
- Guideline (readme) do grupo deve conter código de conduta, guia de contribuição, links para canais de interação, listagem de projetos ativos, links para recursos do grupo etc.
- Recursos e materiais importantes para devem estar organizados em sub-diretórios desse repo
- As lista de exercícios e pequenos estudos do grupo devem estar organizadas no sub-diretório "/exercises"
- Naturalmente, acho que o forum do grupo pode migrar para esse repositório (hoje fica dentro do /study-group.

3. Cada grupo poderá criar e manter projetos em repositório independentes dentro do TC
- Assim como o index, esse repo deve seguir uma convenção de nome (ex: "sg-js-chatbot-eleitor")
- Os moderadores do grupo terão o poder de criar o repositório e serão responsáveis por isso.
- Esses repositórios podem ter uma dinâmica de status como, por exemplo, "Em Desenvolvimento", "Em Manutenção" e "Sem Mantenedor"
* Opinião: não acho que um grupo deveria ter mais de um projeto em status de "Em Desenvolvimento" por vez.
- Os moderadores serão responsáveis por organizar o sistema de votação dos projetos.
* !IMPORTANT: precisamos discutir quais são as regras para que um projeto de um grupo vire um repo.

**Comment by woliveiras** [comment]
Galera, o projeto foi reestruturado e essa issue já não faz mais sentido.

Obrigado pela participação. :heart:
