### ISSUE TITLE
Definição de formato de repositórios para os grupos de estudos

### ISSUE THREAD

**Issue by woliveiras** [training-center/study-groups#66]
O @Diego-Brocanelli  abriu uma issue muito importante (https://github.com/training-center/study-groups/issues/63) para futuras definições do Study Groups.

Ele questionou sobre a criação de um repositório para o grupo de estudos de PHP/POO.

Discutimos no Slack e chegamos a seguinte conclusão:

Podemos criar repositórios para cada projeto que os grupos de estudos forem desenvolver.

Isso vai os ajudar em:

- aprender a documentar um projeto, afinal ele estará disponível abertamente no GitHub
- aprender a trabalhar melhor em equipe usando issues e o projects do GitHub
- se o time utilizar alguma metodologia ágil, as pessoas poderão aprender isso
- a equipe vai aprender a se comunicar melhor

**Comment by woliveiras** [comment]
No nosso repositório principal (esse aqui) podemos ter uma lista de repositórios dos projetos dos grupos.

Ex.:

## Projetos

| grupo | projeto |
| --- | --- |
| php/poo 2017 |  [pastel orientado a objetos](); [kibe com herança múltipla até dizer chega](); [pizza de classes Javaneiras misturadas com repositórios de funções PHP]() |

**Comment by lucianobarauna** [comment]
Acho que organizar isso em projetos seria ótimo mesmo principalmente para quem quer usar mais o github e etc... 
Os grupos no slack creio que seriam mais para a galera se encontrar e trocar idéias.

**Comment by Diego-Brocanelli** [comment]
@woliveiras podemos então já criar as orgs e passarmos os links para o CT inserir aqui neste repositório?

**Comment by woliveiras** [comment]
@Diego-Brocanelli te adicionei na nossa organização para podermos começar esse trabalho.

Vamos fazer o seguinte: criamos o repositório do projeto que vocês vão desenvolver agora e já linkamos no documento aqui neste repô seguindo o formato que comentei aqui https://github.com/training-center/study-groups/issues/66#issuecomment-330396462.

Que tal?

**Comment by Diego-Brocanelli** [comment]
Perfeito @woliveiras  daremos continuidade desta maneira.

**Comment by woliveiras** [comment]
Galera, o projeto foi reestruturado e essa issue já não faz mais sentido.

Obrigado pela participação. :heart:
