### ISSUE TITLE
Corujão

### ISSUE THREAD

**Issue by LGullaci** [training-center/study-groups#68]
Fala Galera,

   Acharia interessante fazermos corujões sobre qualquer tecnologia, mas que seria esse corujão? Seria basicamente um meetup, porém o foco seria estudar uma tecnologia em especifico onde passaríamos a noite e madrugada desenvolvendo mini projetos, analisando código, discutindo boas praticas e por ai vai.

Essa é a ideia inicial, mandem sugestões, criticas e outras ideias também.

Abraço a todos

**Comment by alinebastos** [comment]
Eu não consigo me planejar com antecedência pra essas coisas, mas se pegar um sábado que eu possa, tô dentro!

**Comment by alannaidon** [comment]
Apoio a ideia ! 
Porém, seria presencial certo ? Eu moro longe de todo mundo :cry:

**Comment by alinebastos** [comment]
Não, teria que ser online, senão eu tb não participo, hehe.

**Comment by LGullaci** [comment]
Acho melhor online, porque acho que seria meio complicado encontrar um lugar com uma internet boa, sem contar também a quantidade de pessoas.

**Comment by davidallysson** [comment]
Massa a ideia! Se for sábado pra domingo dá super certo pra mim.

**Comment by Baco23** [comment]
Não tenho experiência em programação. Estou começando a aprender. Posso
participar  como ouvinte?

Att

Em 4 de out de 2017 6:51 PM, "David Allysson" <notifications@github.com>
escreveu:

**Comment by woliveiras** [comment]
IDEIA SHOW DE BOLA, @LGullaci!!!

Você consegue tocar a liderança desse grupo?

**Comment by LGullaci** [comment]
@woliveiras 

     Claro.... Vou montar um template pro corujão
@Baco23 

  Com certeza, qualquer pessoa pode participar... Podemos ter pessoas com bastante conhecimento e outras nem tanto e ideia desse corujão é que todos aprendam e/ou ensinem algo.

**Comment by andregaldino** [comment]
Legal, gostei bastante da ideia, gostaria de participar também.

**Comment by woliveiras** [comment]
Me chama no slack pra gente trocar mais ideia de como tudo isso vai funcionar, @LGullaci 

:raised_hands:

**Comment by alinebastos** [comment]
Opa, nos chama! :P

**Comment by leonantvrs** [comment]
boa @LGullaci , se for final de semana me ajuda...

**Comment by stoque** [comment]
Muito boa a ideia, se rolar mesmo eu fecho :)

**Comment by jorginhodev** [comment]
se for online gostaria de participar...
caso de precisem de ajuda podem contar comigo

**Comment by woliveiras** [comment]
Galera, essa ideia é muito fera.

Bora seguir com esse grupo de estudos no outro repo: https://github.com/training-center/corujao/issues/1

Vou fechar a issue para que as informações sobre o grupo sejam centralizadas lá
