### ISSUE TITLE
Grupo de estudos de Ruby

### ISSUE THREAD

**Issue by gionaufal** [training-center/study-groups#70]
Surgiu no Slack a ideia de formar um grupo de estudos sobre Ruby. Eu pensei em fazermos algo que pode seguir como base a grade do [Odin Project](https://www.theodinproject.com/courses?ref=homenav), pegando os fundamentos de Ruby e depois entrando em frameworks (Sinatra, Rails, Hanami). O que acham?

**Comment by lbighetti** [comment]
Eu me interesso o/

**Comment by maiconkcond** [comment]
Eu me interesso também :)  :+1:

**Comment by gionaufal** [comment]
Digam aí o que acham da proposta que fiz, se tem mais materiais para acrescentar, um outro roadmap (para substituir ou adicionar esse), etc ;)

**Comment by sullyvannunes** [comment]
Ola galera. Sou estagiário de ruby on rails na qconcursos. Tenho muitas coisas pra aprender mas acredito que também tenho experiencias maneiras pra compartilhar :). Me interesso por essa ideia e tenho alguns livros de ruby on rails pra ajudar nesse grupo

**Comment by renancarvalhoo** [comment]
to dentro

**Comment by jamessom** [comment]
tbem tô dentro

**Comment by lucasprag** [comment]
Eu tbm estou dentro o/

**Comment by lbighetti** [comment]
eu não vou conseguir me juntar nesse, estou em muitos já 🤣 
mas parece ter gente o suficiente @gionaufal .

Posso te colocar de organizador e ai você inicia os trabalhos ? :)
hehehe

**Comment by vnbrs** [comment]
Estou dentro!

**Comment by gionaufal** [comment]
Pode sim @lbighetti!

**Comment by lucasprag** [comment]
Então vai rolar? @gionaufal @lbighetti

**Comment by gionaufal** [comment]
vai sim @lucasprag. Vou criar o repo logo mais e vejo como criamos a sala no slack :)

**Comment by aline-aline** [comment]
Também gostaria de participar =)

**Comment by gionaufal** [comment]
repo criado, gente bonita! https://github.com/training-center/ruby-study-group. Estamos também com o canal #ruby-studies lá no slack ;)

**Comment by Diego-Brocanelli** [comment]
Olá, @gionaufal. 

Como o repositório e o grupo de estudos já foram criados, posso encerrar essa issue?

**Comment by gionaufal** [comment]
Claro, pode sim @Diego-Brocanelli ! Valeu
