### ISSUE TITLE
Grupo de estudos ELIXIR

### ISSUE THREAD

**Issue by lbighetti** [training-center/study-groups#71]
Gostaria de montar uma grupo de estudos para estudar [Elixir](https://elixir-lang.org/)

Comentem aqui quem tem interesse e disponibilidade !

![elixir](https://elixir-lang.org/images/logo/logo.png)

**Comment by joaothallis** [comment]
Eu tenho interesse XD! Estou disponível quase todos os dias.

**Comment by gionaufal** [comment]
quero!

**Comment by renancarvalhoo** [comment]
to dentro

**Comment by rodrigooler** [comment]
Estou dentro!

**Comment by felipsimoes** [comment]
To nessa!

**Comment by lbighetti** [comment]
Criado galera!
Repo em https://github.com/training-center/elixir-study-group
Bora pro slack em `#elixir-studies`!

@rodrigooler não te achei no slack mano! tenta lá!
