### ISSUE TITLE
Grupo de estudos FRONT-END

### ISSUE THREAD

**Issue by leonantvrs** [training-center/study-groups#75]
Com objetivo de dar continuidade aos nossos estudos, surgiu a ideia de criar um grupo de estudos sobre tecnologias front-end. Para fazer o fluxo correto do projeto estou criando essa issue.

Já temos algumas pessoas com interesse, então foi marcada uma reunião para quinta-feira dia 07/12 as 22hrs para definir como iremos fazer, aos demais interessado junte-se a nós no slack que ja temos um canal e vamos aprender/compartilhar conhecimentos

**Comment by filodox** [comment]
Como faço pra participar?

**Comment by leonantvrs** [comment]
@filodox entra no slack do training center que temos um canal la

**Comment by lbighetti** [comment]
Bom, o grupo foi criado em https://github.com/training-center/frontend-study-group
no slack tem também o channel `frontend-studies`.

Top!
vou fechar o issue, continuemos por lá!
