### ISSUE TITLE
Grupo de Estudos JavaScript

### ISSUE THREAD

**Issue by lbighetti** [training-center/study-groups#77]
Criando esse issue para interessados em criar um grupo de estudos de JavaScript

Lembrando: É necessário no mínimo um organizador + 4 membros, e esses membros serão responsáveis por manter o grupo se reunindo, definindo pauta e planos de estudos.

(Nota: eu **não** tenho interesse de ser organizador nem membro)

**Comment by Lipemenezes** [comment]
Tenho interesse. 😄

**Comment by Morette** [comment]
Opa
Estou interessado

**Comment by otavioarc** [comment]
Tenho interesse!

**Comment by israelmeinert** [comment]
Tenho interesse.

**Comment by AlexsandroSA** [comment]
Tenho interesse! :)

**Comment by pachecovit** [comment]
Tenho interesse tbm!

**Comment by david81brs** [comment]
Dentro

**Comment by crisgon** [comment]
Tenho interesse

**Comment by jorginhodev** [comment]
tenho interesse em ser membro.
alguma novidade sobre o projeto?

**Comment by jeyziel** [comment]
tenho interesse tbm.

**Comment by osamuca** [comment]
também tenho interesse.

**Comment by ricardogouveia3** [comment]
tenho interesse :)

**Comment by juulhao** [comment]
Quero participar!

**Comment by AlexsandroSA** [comment]
Pessoal, tudo bem?

Vamos criar um grupo no slack ou telegram e iniciar os estudos, já que uma galera tem interesse vamos os estudos?

**Comment by Diego-Brocanelli** [comment]
@AlexsandroSA  deve ser criado um grupo no Slack, para isso o grupo deve conter:

- Organizador
    - A responsabilidade do organizador é liderar o grupo.
    - Não é responsabilidade do organizador ficar ensinando, isso é do grupo como um todo :)
- Mínimo de 4 membros.

Após definição desses pontos basta entrar no Slack do Training Center e solicitar ao Willian a criação do grupo.

**Comment by AlexsandroSA** [comment]
@Diego-Brocanelli muito obrigado!. Vou solicitar ao Willian a criação do grupo. 

Valeu! :)

**Comment by Diego-Brocanelli** [comment]
@AlexsandroSA assim que criar o grupo, jogue o nome aqui, abra a PR para o Study Groups e fecha a issue :) 

Sucesso nos estudos do grupo :)

**Comment by AlexsandroSA** [comment]
Pessoal, grupo criado!. Nome: __javascript-studies__

**Comment by Diego-Brocanelli** [comment]
Obrigado @AlexsandroSA  e boa sorte nos estudos do grupo.
