### ISSUE TITLE
Separar a tabela de grupos ativos

### ISSUE THREAD

**Issue by woliveiras** [training-center/study-groups#78]
Hoje temos a tabela de grupos ativos no documento principal, mas com o crescimento da quantidade de grupos isso vai ficar ruim por conta do tamanho do README.

Seria legal criar um arquivo separado só para listagem dos grupos.

cc: @lbighetti

**Comment by Diego-Brocanelli** [comment]
Acredito que seja melhor mesmo a criação de um arquivo listando os grupos de estudos. Realmente ficará extenso a lista e o README conforme a inserção dos novos grupos.
Posso ficar responsável pela criação do diretório e atualização do README, imagino a seguinte estrutura:

- grupos
    - GRUPOS.md

- README.md
    - Atualização para inserção do link de acesso ao novo arquivo.

O que acham?

**Comment by lbighetti** [comment]
@woliveiras @Diego-Brocanelli 
Temos 4 grupos por enquanto, vocês acham difícil / confuso deixar no readme principal ?

**Comment by lbighetti** [comment]
Ah, dei merge. Se ficar ruim a gente reverte 👍 
Thanks @Diego-Brocanelli !
