### ISSUE TITLE
Grupo de estudos Python

### ISSUE THREAD

**Issue by cvalentefilho** [training-center/study-groups#79]
Conversei com o @woliveiras e gostaria de iniciar um grupo de estudo de Python.

**Comment by adrianoavelino** [comment]
Algumas vezes por semana estou dando umas olhada no python, coisas básicas. Dependendo de como for posso participar também. Já pensou de participar do [dojo](https://github.com/training-center/dojos) que ocorre nos sábados pro pessoal se animar mais?

**Comment by lbighetti** [comment]
Eu to dentro o/

**Comment by Morette** [comment]
Opa
Não sei como funciona, mas gostaria de participar.

**Comment by afonsoaugusto** [comment]
Acho super valido...

**Comment by mauraodev** [comment]
Opa, to dentro, comecei a estudar python a pouco tempo

**Comment by filodox** [comment]
tambem to dentro

**Comment by cvalentefilho** [comment]
Galera criei o repo https://github.com/training-center/python-study-group e já estamos com o canal no slack me deem um ping lá pra adicionar vcs @cvalente

**Comment by jonatanvianna** [comment]
To dentro

**Comment by TiagoHA** [comment]
Presencial?

**Comment by ThaisNunes01** [comment]
Como faço pra participar?

**Comment by Neto1351** [comment]
Quero participar! Como faço?

**Comment by adrianoavelino** [comment]
Se a não entrou entre no  slack do Training center https://github.com/training-center/slack e entre no channel #python-studies que o pessoal á está se comunicando por lá

**Comment by Diego-Brocanelli** [comment]
Pessoal, como o grupo já foi criado podemos encerrar essa issue?

**Comment by mrprompt** [comment]
topo!
