### ISSUE TITLE
O Processo de Fork e transferir de volta não está funcionando

### ISSUE THREAD

**Issue by lbighetti** [training-center/study-groups#81]
https://monosnap.com/file/k5WN2yOk3w7bz29GMaVo9W3ImcnI7Y

**Comment by woliveiras** [comment]
Eita!

Vou verificar isso, mano!

Obrigado pelo report.

**Comment by Diego-Brocanelli** [comment]
@woliveiras conseguiu analisar o bug, para podermos fechar essa issue?

**Comment by woliveiras** [comment]
Arrumei, galera!

Está aqui: https://github.com/training-center/template-study-group

Podem validar e dar um OK aqui para fecharmos a issue se estiver tudo certo.

**Comment by woliveiras** [comment]
Testaram, galera?

**Comment by Diego-Brocanelli** [comment]
@woliveiras acredito que pode ser encerrado a issue.

**Comment by lbighetti** [comment]
@alexsandrosa está com esse problema novamente

**Comment by woliveiras** [comment]
Eita! Como você fez o processo, @AlexsandroSA?

**Comment by AlexsandroSA** [comment]
Sou ninja @woliveiras  - kkk³ - zueira. O @luizbills fez a gentileza de criar e depois transferiu :)

**Comment by woliveiras** [comment]
HAHIAHIAHIAIH

Fizeram seguindo [esse](https://github.com/training-center/template-study-group) esquema?

**Comment by AlexsandroSA** [comment]
Acredito que sim!. Fiz um baseado nesse esquema, só deu problema de permissão quando tentei transferir para o git do CT. 

Eu acho que o @lbighetti fez um fork do que já tinha feito e transferiu.

**Comment by woliveiras** [comment]
Saquei.

Vou fechar a issue e qualquer problema revivemos ela.
