### ISSUE TITLE
Grupo de estudos JAVA

### ISSUE THREAD

**Issue by Morette** [training-center/study-groups#83]
E aí pessoal, como não vi ninguém falando sobre Java e essa é uma linguagem que me interessa, estou criando essa issue, porém não poderei ser o organizador. Ficarei como participante.

**Comment by rodrigobravo** [comment]
Tenho interesse me participar !!!!

**Comment by lucasrobaert** [comment]
Tenho interesse em participar!

**Comment by myakiju** [comment]
Tenho interesse em participar também

**Comment by fabiomsnet** [comment]
Que legal!! Também tenho interesse em participar do grupo :)

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal!

Sou um dos líderes do **study-groups**.

Para a criação do grupo de estudos de Java são necessários as seguintes informações, sendo:

- **Definição do líder**
    - Responsável por organizar e gerir o grupo.
- **Participantes**
    - Necessário o mínimo de 4 pessoas para a criação do grupo.

Após definido os pontos acima, deve ser solicitado a criação do repositório do grupo de estudos, conforme modelo.

Para qualquer dúvida, por favor insira aqui na Issue ou entre em contato comigo no Slack do Training Center `@DiegoBrocanelli`.

Sucesso com os estudos do grupo :)

**Comment by rafa-maciel** [comment]
Tudo certo pessoal, também tenho interesse em participar!

**Comment by ConradoKraicek** [comment]
Tenho interesse em participar, inclusive tirei agora em novembro/2017 a certificação java 7 OCA

**Comment by Morette** [comment]
@ConradoKraicek você poderia ser o líder então?

**Comment by juulhao** [comment]
Super interessado! +1

**Comment by Diego-Brocanelli** [comment]
@ConradoKraicek você pode assumir como líder do grupo  de estudos? 

Caso positivo por favor entre em contado com o @woliveiras para que seja criado repositório e chanel no Slack.

Caso você não possa liderar, deve ser definido antes das criações mencionadas acima.

**Comment by ConradoKraicek** [comment]
Ola a todos, sou um entusiasta do java, e em constante estudo da linguagem,
tanto que tirei uma certificação e me encaminhando para a próxima, mas acho
que não tenho perfil para líder, mas entusiasmado para participar deste
grupo de estudos.

Atenciosamente,

Conrado A. Cardozo

Em 5 de janeiro de 2018 14:26, Diego Brocanelli <notifications@github.com>
escreveu:

**Comment by otavioprado** [comment]
Oi @Diego-Brocanelli 
Tenho interesse sim, posso ajudar no que for necessário. Vou te procurar no Slack para tirar algumas dúvida, tudo bem? Vamos agitar esse grupo de Java ai, rs.

Pessoal que quiser entrar em contato comigo, estou a disposição.

**Comment by Diego-Brocanelli** [comment]
Perfeito, vamos nos falando.

**Comment by rodrigobravo** [comment]
aguardando ansiosamente esse grupo !!!!


Em sáb, 13 de jan de 2018 às 15:15, Diego Brocanelli <
notifications@github.com> escreveu:

**Comment by Morette** [comment]
Opa, bora lá animar isso aí...

**Comment by ronesp86** [comment]
eu fecho tbm, só aguardando as novidades...

**Comment by SilvaAllan** [comment]
Tenho muito interesse em participar do grupo também!!

**Comment by Morette** [comment]
Já podemos criar um channel no Slack?

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Nosso colega @otavioprado está providenciando a criação do grupo junto ao CT, assim que o mesmo tiver o retorno será posicionado.

**Comment by NicholasPedroso** [comment]
Olá pessoal,

tenho interesse em participar também! =)

**Comment by taciossbr** [comment]
Tenho interesse em participar tbm.

**Comment by rrezenes** [comment]
Também estou super interessado!

**Comment by otavioprado** [comment]
Fala pessoal, 
Channel no slack: java-studies
Repositório no Github: https://github.com/training-center/java-study-group

Let's go :)

**Comment by vicenthy** [comment]
Opa tenho interesse em participar

**Comment by Diego-Brocanelli** [comment]
@otavioprado como o grupo já foi criado, podemos encerrar essa issue?

**Comment by otavioprado** [comment]
@Diego-Brocanelli pode encerrar a issue
