### ISSUE TITLE
Grupo de estudos PHP

### ISSUE THREAD

**Issue by juulhao** [training-center/study-groups#86]
Fala galera, sou front-end, porém quero começar a me aventurar por Back-end, então escolhi PHP como ponto de partida.
Procuro algum responsável para ser mentor deste grupo, e claro, interessados de fazer esse grupo rolar :dancer: 
Abraçoos!

**Comment by Diego-Brocanelli** [comment]
Olá @juulhao excelente escolha, sou o líder do grupo de estudos de PHP, por favor poderia mover essa Issue para o repositório do grupo de estudos de PHP para que possamos ajudar. 

Pois esse repositório é o Hub dos grupos de estudos e nem todos os membros de PHP acessam.

Assim que você abrir a Issue lá, por favor feche essa Issue aqui :)

Grato pela atenção.
