### ISSUE TITLE
Grupo de estudos PHP/Laravel

### ISSUE THREAD

**Issue by EduardoFerreiraJunior** [training-center/study-groups#9]
Formação de grupo para estudar PHP com o framework Laravel.

**Comment by alannaidon** [comment]
Count me in!
Estou desenvolvendo um sistema pra faculdade usando o Laravel.
Acredito que poderia ensinar algumas coisas e aprender bastante também '-'

**Comment by ValdirCamargo** [comment]
To  dentro tbm...

**Comment by ktquez** [comment]
Estou dentro

**Comment by khaosdoctor** [comment]
Estou a fim também

**Comment by gamartins** [comment]
Como entro ?

**Comment by LarissaAbreu** [comment]
@gamartins acessa esse link aqui que é onde a galera está se organizando. Se eu não me engano ainda não tem um grupo formado por causa da quantidade de pessoas mas, se vocês quiserem, eu posso abrir o grupo lá pra vocês :bowtie:

**Comment by mauraodev** [comment]
Se tiver vaga estou dentro

**Comment by woliveiras** [comment]
Já invoca o povo no Slack @mauraodev :smile:

**Comment by rogeralbinoi** [comment]
Se tiver alguma vaga tô dentro tbm

**Comment by woliveiras** [comment]
Os grupos foram movidos para nosso [Slack](https://ctgroups.herokuapp.com/), por isso vou fechar a issue.

Caso seja necessário, podemos reabrir.
