### ISSUE TITLE
Grupo de estudos Blockchain 

### ISSUE THREAD

**Issue by camilaavilarinho** [training-center/study-groups#91]
Estou abrindo essa issue para juntar gente para formar um grupo de estudos sobre blockchain. 

O objetivo é que possamos estudar os assuntos necessários para se tornar um(a) desenvolvedor(a) blockchain. 

Eu tenho muito interesse por essa tecnologia e suas aplicações (além das criptomoedas) mas tenho dificuldade para organizar e me manter motivada a estudar, então acho que juntando com outras pessoas posso fazer isso com mais qualidade, compartilhando e tendo pessoas para conversar sobre o processo de aprendizagem. 

Alguém interessado? :)

**Comment by mrprompt** [comment]
Boa, tenho interesse :)

**Comment by higornunes** [comment]
+1

**Comment by gss-patricia** [comment]
+1

**Comment by TiagoFuelber** [comment]
+1

**Comment by Diego-Brocanelli** [comment]
Olá @camilaavilarinho para que seja criado o grupo de estudos, devem contemplar os seguintes requisitos, sendo:

- ***Líder do grupo.***
    - Responsabilidade:
        - Organizar e gerenciar as atividades, processos e documentações do grupo de estudos.
        - ***Observação:*** Poderia ser você o líder do grupo? Pois agiliza os processos.
- ***Mínimo de 4 membros.***

Após os requisitos estarem acertados, deve ser entrado em contato com o @woliveiras solicitando a criação do repositório no GitHub e channel no Slack.

Após criação do repositório do GitHub, deve ser aberto uma PR no repositório do [study-groups](https://github.com/training-center/study-groups) incluindo o grupo e nome do líder no grid de grupos ativos.

Obrigado pela atenção e sucesso com o grupo de estudos.

**Comment by danielmadu** [comment]
Opa, muito me interessa

**Comment by annielmenezes** [comment]
@camilaavilarinho Tenho interesse em participar do grupo, acho que o pessoal dos comentários com "+1" também, rsrs. Como o @Diego-Brocanelli comentou acima precisamos de um líder e quatro membros que, penso eu já temos, então agora seria criar os passos descritos por ele e começar os :books:

**Comment by iagocavalcante** [comment]
Opa, tenho interesse, inclusive comecei a ler sobre blockchain para segurança em IoT.

**Comment by eptaccio** [comment]
bora

**Comment by crissilvaeng** [comment]
+1

Que material de referência você tem em mente pra servir como base de estudos?

**Comment by locemarn** [comment]
topo!!

**Comment by camilaavilarinho** [comment]
Oi pessoal, 
Obrigada pelo interesse! 
Aqui algumas coisas sobre o andamento do grupo: 

- Já temos um [repositório para o grupo](https://github.com/training-center/blockchain-study-group)

- Canal no slack: `#blockchain-studies`  (entrem lá)

- Estou preparando um formulário para poder alinhar o conhecimento de todo mundo (em breve coloco o link no repositório)

**Comment by camilaavilarinho** [comment]
@crissilvaeng sobre o material ainda estou pesquisando e tbm tentando entrar em contato com alguns devs para pedir opinião, mas a definição do material mesmo acho que é uma coisa que podemos fazer juntos e decidir na nossa primeira reunião (pq tbm vai depender do nível de conhecimento e do interesse dos participantes)

**Comment by anabastos** [comment]
Tenho interesse 😸 
+1

**Comment by camilaavilarinho** [comment]
Pessoal, o formulário já está criado, respondam aqui: https://goo.gl/forms/yIzW4Z5Mx1EdufZR2 

E entrem no slack para a gente conversar sobre o grupo por lá ;) 

@mrprompt @higornunes @gss-patricia @TiagoFuelber @danielmadu @annielmenezes @iagocavalcante @eptaccio @crissilvaeng @locemarn @anabastos

**Comment by Diego-Brocanelli** [comment]
@camilaavilarinho como o grupo já foi criado podemos encerrar essa issue?

**Comment by camilaavilarinho** [comment]
@Diego-Brocanelli sim
