### ISSUE TITLE
Grupo de estudos de Go

### ISSUE THREAD

**Issue by brunogbr** [training-center/study-groups#93]
Procuro pessoas interessadas em um grupo de estudos de Go, posso ficar de lider do grupo.

A linguagem Go vem crescendo bastante no mercado brasileiro e já é muito usada no exterior, acredito que um grupo no TC seria bem util para todxs.

**Comment by amadeu01** [comment]
Gostaria de participar!!

**Comment by OswaldoRMarques** [comment]
Eu também gostaria de participar!

**Comment by WendellAdriel** [comment]
Comecei a estudar Go há mais ou menos um ano e quero participar e se precisar de ajuda conte comigo @brunogbr

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal!

Sou um dos líderes do study-groups.

Para a criação do grupo de estudos de Go são necessários as seguintes requisitos, sendo:

- ***Definição do líder***
    - Responsável por organizar e gerir o grupo.
- ***Participantes***
    - Necessário o mínimo de 4 pessoas para a criação do grupo.

Após definido os pontos acima, deve ser solicitado a criação do repositório do grupo de estudos, conforme modelo.

Para qualquer dúvida, por favor insira aqui na Issue ou entre em contato comigo no Slack do Training Center @DiegoBrocanelli.

Sucesso com os estudos do grupo :)

**Comment by natandrake** [comment]
Quero participar também

**Comment by brunogbr** [comment]
Boa tarde @Diego-Brocanelli , to seguindo os passos da criação do repositório, na parte de transferência ta dando erro, diz que não tenho autorização para criar um repositório para training-center. Como proceder?

**Comment by Diego-Brocanelli** [comment]
Olá, @brunogbr.

Estou analisando e assim que obtiver a resposta lhe comunico.

**Comment by devendpro** [comment]
Gostaria de participar do grupo de estudos.

**Comment by lithium-x** [comment]
Também tenho vontade de participar.

**Comment by WendellAdriel** [comment]
Alguma novidade sobre o grupo @brunogbr e @Diego-Brocanelli ???

**Comment by Diego-Brocanelli** [comment]
@WendellAdriel  não, a resolução encontra-se em andamento.

**Comment by ansellmo-jorge** [comment]
Sou estudante da linguagem Python e achei Go interessante. Gostaria de poder fazer parte do grupo

**Comment by brunogbr** [comment]
@WendellAdriel To aguardando, tive esse problema da transferência e o Diego esta verificando pra gente. Mas vai sair \o/

**Comment by Diego-Brocanelli** [comment]
@brunogbr  e @WendellAdriel  Já entrei em contato com o @woliveiras  e o mesmo está providenciando a resolução da eventualidade da transferência do repositório.

**Comment by Diego-Brocanelli** [comment]
@brunogbr Você reveberá um e-mail para entrar no ***study-groups***, após aceitar o convite realize o processo de migração do repositório.

Qualquer dúvida favor me acionar.

**Comment by brunogbr** [comment]
@Diego-Brocanelli Ainda ta dando que eu não tenho permissões. Vou aguardar mais um tempo e tentar mais tarde. 

" You don’t have the permission to create repositories on training-center "

**Comment by Diego-Brocanelli** [comment]
Você recebeu o email que mencionei?

**Comment by brunogbr** [comment]
Sim, já aceitei e entrei no grupo. Vou esperar mais um pouco porque um pessoal tava reclamando de instabilidade no github de novo, de repente é isso..

**Comment by edias15** [comment]
I gostaria de participar.

**Comment by Diego-Brocanelli** [comment]
@brunogbr crie o repositório, com isso faça o clone e siga com o grupo. https://github.com/training-center/go-study-groups

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

A channel `#go-studies` foi criada no slack, bons estudos a todos.

**Comment by ansellmo-jorge** [comment]
Boas,  os estudos vāo se basear  em alguma area especifica? visto que o Go é uma linguagem de propósito geral.

**Comment by Diego-Brocanelli** [comment]
Pessoal, como todo o processo foi finalizado, será encerrado essa issue referente ao start do grupo de estudos.
