### ISSUE TITLE
 Grupo de estudos de Rust

### ISSUE THREAD

**Issue by giovannism20** [training-center/study-groups#94]
Criando essa issue para interessados em participar do grupo de estudos de Rust.
Lembrando: É necessário no mínimo um organizador(**EU**) + 4 membros.
**Rust tem apoio da Mozilla** <3. É responsável pelo [servo](https://github.com/servo/servo) que roda no [Firefox Quantum](https://www.mozilla.org/pt-BR/firefox/)

[Mozilla Rust Roadshow](https://discourse.mozilla.org/t/anunciando-o-rust-roadshow-brasil-2018-para-mobilizadores-de-todo-o-brasil/23321) | O Roadshow será um conjunto de workshops organizados (pela própria comunidade) entre os dias 2-4 de Fevereiro/2018, para disseminar a linguagem no Brasil.
[Roadshow na sua cidade :D](https://rust-br.github.io/2018-roadshow/)

[Me](http://bit.ly/2nf5EQn)

@martins_giovanni (Slack TC)
[@martins_giovanni (Telegram)](https://t.me/martins_giovanni)

[Comunidade BRASILEIRA](https://github.com/rust-br)
[Telegram RustBR](https://t.me/rustlangbr)

**Comment by Diego-Brocanelli** [comment]
Bom dia @GiovanniSM20  sou o líder dos grupos de estudos, está precisando de ajuda para montar o grupo, estou a disposição para lhe auxiliar na aquisição de membros.

**Comment by GiovanniSM20** [comment]
fala @Diego-Brocanelli tudo bom ? bom dia!

Não sei se preciso de ajuda ou talvez só tenha faltado interesse por parte da galera, o que acha ?

**Comment by Diego-Brocanelli** [comment]
Olá, @GiovanniSM20 
Pode ter ocorrido as duas coisas, normalmente a galera perde a empolgação, e ficam muito passivos, esperando que alguém movimente a roda, o que é normal, infelizmente.

Mas caso queriam podemos tentar captar membros usando nossas redes sociais, fico no aguardo.

**Comment by GiovanniSM20** [comment]
@Diego-Brocanelli Gostaria bastante de receber ajuda, por onde começamos ?

**Comment by Diego-Brocanelli** [comment]
@GiovanniSM20 Me acione individualmente no Slack para que possamos alinhar a melhor forma  `@Diego Brocanelli` :)

**Comment by GiovanniSM20** [comment]
@Diego-Brocanelli No canal do Training Center mesmo ?

**Comment by Diego-Brocanelli** [comment]
Sim!

**Comment by GiovanniSM20** [comment]
Chamei @Diego-Brocanelli
