### ISSUE TITLE
Sobre congelamento de grupos de estudos

### ISSUE THREAD

**Issue by pacheco7** [training-center/study-groups#95]
Pessoal,

Estou no controle da organização do #71 , tentei diversas vezes organizar reuniões, porém sem sucesso (por falta de participação da galera lá inscrita). Acredito que o congelamento deste seria o caminho correto a se seguir e para tal, como podemos realizar esta ação?

**Comment by Diego-Brocanelli** [comment]
@pacheco7 como foi o processo para a escolha do formato das reuniões?

Uma opção válida seria criando um form para que os membros votassem no melhor dia e horário para realizar as reuniões.

No grupo de estudos de PHP, foi definido inicialmente que as reuniões quando ocorrerem devem ser as quartas ferisa das 21:00 às 22:00

**Comment by woliveiras** [comment]
As vezes rola da galera chegar animada e depois de um tempo sumir mesmo

É um trabalho pessoal buscar motivação para estudar quando estudamos por conta

A gente até consegue ajudar motivar outras pessoas, mas se não rolar o exercício de buscar motivação pessoal naquilo que está fazendo, logo o pessoal abandona...

Talvez tenha rolado isso :cry: 

Sobre o processo de **congelamento**, ainda não havíamos discutido isso...

Acho que podería só colocar um badge aqui na lista de grupos ativos com um :snowflake:, informando que o grupo está congelado e precisa de gente ativa de novo para voltar.

Teríamos que informar como reativar o grupo e isso eu não tenho ideia. :joy:

**Comment by pacheco7** [comment]
@Diego-Brocanelli foram tentadas em diversas formas, por forms, por threads, a galera escolheu, porém chegava a data e ninguém aparecia...

**Comment by Diego-Brocanelli** [comment]
Realmente parte do comprometimento individual, e caso seja realizado o congelamento podemos analisar esse processo.

**Comment by pacheco7** [comment]
@woliveiras no grupo tentamos (eu e o @lbighetti) motivar a galera para estudar, somente 1 teve interesse até então...

Eu indicaria no processo de congelamento um prazo para voltar, tipo uns 3 meses, por exemplo. Caso o atual organizador não quisesse mais tal função, abriríamos o espaço para um novo organizador. Outra indicação que deixaria seria tornar os grupos de estudos no slack no modo privado, pois assim só entrariam pessoas que aqui quiseram estudar (comentando nas Issues). Poderíamos neste caso ainda fazer um form de triagem e postar no slack, caso a galera não tenha visto a Issue do grupo de estudos.

**Comment by WendellAdriel** [comment]
Na minha opinião, congelar um grupo de estudo é algo mais complicado e subjetivo. Para criar tal processo teríamos de definir muitas coisas e acho que é algo muito burocrático e demorado para fazer sendo que temos muitos outros assuntos para tratar.

Pessoalmente eu acho que desde que tenham 3 pessoas ativas (entendendo como ativa a pessoa que interage em um grupo pelo menos uma vez na semana, seja perguntando ou respondendo algo, enviando links, etc) o grupo está funcional. Pode não ser a situação ideal, mas mesmo assim está a ter aprendizado e troca de conhecimentos. 

Contudo alguns pontos que acho importante ressaltar sobre o **study-groups** no geral são:

- O **"líder"** do grupo deve sempre se manter ativo e tentando motivar os outros membros, caso contrário deve ser colocada outra pessoa

- Para formar o grupo, além das ações já realizadas: ter um número mínimo de membros, ter um **"líder"**, etc, o líder deve criar um pequeno e simples formulário com perguntas relacionadas ao grupo como: melhor horário para reunião, etc.

- Depois do grupo formado: repo e channel já criados, deveria se ter uma issue aberta fixa no repo do grupo com uma label **Form** ou algo parecido com um link para quem quiser participar do grupo responder ao form criado no item anterior.

- O channel dos grupos no Slack passariam todos para privados para ter apenas pessoas que realmente  têm interesse no grupo.

- Caso um grupo fique sem um líder ou com menos de três pessoas ativas, deve ser criado uma issue no repo do grupo que ficará aberta por um período a definir (por exemplo um ou dois meses) e caso a situação não altere o channel no Slack é deletado e o repo passa a ter uma indicação no README que o grupo está inativo e uma issue fixa em aberto com uma label **Inactive** ou algo parecido onde pode se começar o processo de ativação novamente: encontrar x membros, etc.

**Comment by pacheco7** [comment]
Concordo com os últimos itens que você apontou @WendellAdriel. Sobre abrir uma Issue nova, como ela poderia ser chamada, na sua opinião?

**Comment by WendellAdriel** [comment]
A issue fixa do **Form** acho que poderia se chamar: `Form de inscrição para o grupo de estudos` e a issue fixa para tentar reativar novamente o grupo poderia se chamar: `GRUPO INATIVO - Discussão para reativar grupo`

**Comment by Diego-Brocanelli** [comment]
Bom dia, essa issue ainda se mostra relevante, ou podemos encerrar?
